# Generated by Django 4.0 on 2022-03-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='next',
        ),
    ]
