# Generated by Django 4.0 on 2022-03-09 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuessinessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='name')),
                ('expression', models.CharField(blank=True, default='completed', max_length=1024, null=True, verbose_name='规则')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='事件描述')),
                ('buessiness_rule_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='业务规则ID')),
            ],
        ),
        migrations.AddField(
            model_name='serviceoperations',
            name='next_operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_operation', to='define_operand.operation', verbose_name='后续作业'),
        ),
        migrations.AlterField(
            model_name='serviceoperations',
            name='operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation', to='define_operand.operation', verbose_name='作业'),
        ),
        migrations.AddField(
            model_name='serviceoperations',
            name='buessiness_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.buessinessrule', verbose_name='规则'),
        ),
    ]
