# Generated by Django 4.0 on 2022-03-20 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0001_initial'),
        ('define_operand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buessinessform',
            name='managed_entities',
            field=models.ManyToManyField(through='define_operand.FormEntityShip', to='define.ManagedEntity', verbose_name='关联实体'),
        ),
        migrations.AlterField(
            model_name='service',
            name='managed_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='define.managedentity', verbose_name='管理实体'),
        ),
    ]
