# Generated by Django 4.0 on 2022-06-19 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0002_alter_characterfield_label_alter_characterfield_name_and_more'),
        ('define_operand', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtenalServiceFieldsMapping',
            new_name='ExternalServiceFieldsMapping',
        ),
    ]
