# Generated by Django 4.0 on 2022-03-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='operations',
            field=models.ManyToManyField(through='define_operand.OperationsSetting', to='define_operand.Operation', verbose_name='包含作业'),
        ),
    ]
