# Generated by Django 4.0 on 2023-04-05 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0001_initial'),
        ('define_operand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputeComponentsSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='计算字段说明')),
                ('js_script', models.TextField(blank=True, max_length=255, null=True, verbose_name='计算脚本')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='define.component', verbose_name='字段')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='define_operand.buessinessform', verbose_name='表单')),
            ],
            options={
                'verbose_name': '计算字段设置',
                'verbose_name_plural': '计算字段设置',
            },
        ),
    ]
