# Generated by Django 4.0 on 2022-03-15 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_rule_dict', '0001_initial'),
        ('define_operand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicessetting',
            name='check_awaiting_timeout',
            field=models.BooleanField(default=False, verbose_name='检查等待超时'),
        ),
        migrations.AddField(
            model_name='servicessetting',
            name='check_execution_timeout',
            field=models.BooleanField(default=False, verbose_name='检查执行超时'),
        ),
        migrations.AlterField(
            model_name='operationssetting',
            name='passing_data',
            field=models.PositiveSmallIntegerField(choices=[(0, '否'), (1, '接收，不可编辑'), (2, '接收，可以编辑')], default=0, verbose_name='接收表单'),
        ),
        migrations.AlterField(
            model_name='servicessetting',
            name='complete_feedback',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '否'), (1, '返回完成状态'), (2, '返回表单')], default=0, null=True, verbose_name='完成反馈'),
        ),
        migrations.AlterField(
            model_name='servicessetting',
            name='interval_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_rule_dict.intervalrule', verbose_name='服务时间间隔'),
        ),
        migrations.AlterField(
            model_name='servicessetting',
            name='passing_data',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '否'), (1, '接收，不可编辑'), (2, '接收，可以编辑')], default=0, null=True, verbose_name='接收表单'),
        ),
    ]
