# Generated by Django 4.0 on 2022-03-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buessinessform',
            name='buessiness_form_id',
        ),
        migrations.RemoveField(
            model_name='formentityship',
            name='form_entity_ship_id',
        ),
        migrations.AddField(
            model_name='buessinessform',
            name='hssc_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID'),
        ),
        migrations.AddField(
            model_name='formentityship',
            name='hssc_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID'),
        ),
        migrations.AddField(
            model_name='formentityship',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='formentityship',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='buessinessform',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='buessinessform',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
    ]
