# Generated by Django 4.0 on 2022-03-17 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='forms',
            new_name='form',
        ),
    ]
