# Generated by Django 4.0 on 2023-05-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buessinessform',
            name='form_style',
            field=models.CharField(choices=[('Detail', '详情'), ('List', '列表')], default='Detail', max_length=20, verbose_name='表单风格'),
        ),
        migrations.AlterField(
            model_name='eventrule',
            name='form_class_scope',
            field=models.PositiveSmallIntegerField(choices=[(0, '所有类型'), (1, '调查类'), (2, '诊断类'), (3, '治疗类')], default=0, verbose_name='表单类型范围'),
        ),
    ]
