# Generated by Django 4.0 on 2022-03-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='excute_datetime',
            field=models.DurationField(blank=True, null=True, verbose_name='执行时间'),
        ),
        migrations.AddField(
            model_name='service',
            name='excute_datetime',
            field=models.DurationField(blank=True, null=True, verbose_name='执行时间'),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
    ]
