# Generated by Django 4.0 on 2022-03-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DesignBackup',
        ),
        migrations.DeleteModel(
            name='SourceCode',
        ),
    ]
