# Generated by Django 4.0 on 2022-05-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrule',
            name='detection_scope',
            field=models.CharField(blank=True, choices=[('ALL', '所有历史表单'), ('CURRENT_SERVICE', '本次服务表单'), ('LAST_WEEK_SERVICES', '过去7天表单')], default='CURRENT_SERVICE', max_length=100, null=True, verbose_name='检测范围'),
        ),
    ]
