# Generated by Django 4.0 on 2022-02-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='事件ID'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='instruction_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='指令ID'),
        ),
        migrations.AddField(
            model_name='operation',
            name='operand_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='作业ID'),
        ),
        migrations.AddField(
            model_name='role',
            name='role_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='角色ID'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='单元服务ID'),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='service_package_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='服务包ID'),
        ),
    ]
