# Generated by Django 4.0 on 2022-04-20 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceProgramSetting',
            new_name='ServiceRule',
        ),
    ]
