# Generated by Django 4.0 on 2023-08-11 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='arrange_service_package',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.servicepackage', verbose_name='安排服务包'),
        ),
    ]
