# Generated by Django 4.0 on 2022-03-11 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_icpc', '0001_initial'),
        ('define', '0002_alter_component_options_alter_dicdetail_options_and_more'),
        ('define_operand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuessinessForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('label', models.CharField(max_length=100, unique=True, verbose_name='表单名称')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='表单说明')),
                ('meta_data', models.JSONField(blank=True, null=True, verbose_name='元数据')),
                ('buessiness_form_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='业务表单ID')),
                ('components', models.ManyToManyField(blank=True, to='define.Component', verbose_name='字段')),
                ('components_groups', models.ManyToManyField(blank=True, to='define.ComponentsGroup', verbose_name='组件')),
            ],
            options={
                'verbose_name': '业务表单',
                'verbose_name_plural': '业务表单',
            },
        ),
        migrations.AlterModelOptions(
            name='systemoperand',
            options={'ordering': ['id'], 'verbose_name': '系统自动作业', 'verbose_name_plural': '系统自动作业'},
        ),
        migrations.CreateModel(
            name='FormEntityShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_base_infomation', models.BooleanField(default=False, verbose_name='基本信息表')),
                ('form_entity_ship_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='实体表单关系ID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='define.managedentity', verbose_name='隶属实体')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='define_operand.buessinessform', verbose_name='业务表单')),
            ],
            options={
                'verbose_name': '表单和实体关系',
                'verbose_name_plural': '表单和实体关系',
            },
        ),
        migrations.AddField(
            model_name='buessinessform',
            name='managed_entity',
            field=models.ManyToManyField(blank=True, through='define_operand.FormEntityShip', to='define.ManagedEntity', verbose_name='隶属实体'),
        ),
        migrations.AddField(
            model_name='buessinessform',
            name='name_icpc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_icpc.icpc', verbose_name='ICPC编码'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='forms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.buessinessform', verbose_name='作业表单'),
        ),
    ]
