# Generated by Django 4.0 on 2022-10-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventexpression',
            name='value',
        ),
        migrations.AlterField(
            model_name='eventexpression',
            name='operator',
            field=models.PositiveSmallIntegerField(choices=[(0, '=='), (1, '!='), (2, '>'), (3, '<'), (4, '>='), (5, '<=')], null=True, verbose_name='操作符'),
        ),
    ]
