# Generated by Django 4.0 on 2022-03-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='begin_time_setting',
            field=models.PositiveSmallIntegerField(choices=[(0, '默认当前时间'), (1, '人工指定时间'), (2, '引用出生日期')], default=0, verbose_name='开始时间设置'),
        ),
    ]
