# Generated by Django 4.0 on 2022-03-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['id'], 'verbose_name': '事件', 'verbose_name_plural': '事件'},
        ),
        migrations.AlterModelOptions(
            name='eventroute',
            options={'ordering': ['id'], 'verbose_name': '事件后续作业', 'verbose_name_plural': '事件后续作业'},
        ),
        migrations.AlterField(
            model_name='operandintervalrule',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='operandintervalrule',
            name='interval',
            field=models.DurationField(blank=True, help_text='例如：3 days, 22:00:00', null=True, verbose_name='间隔时间'),
        ),
        migrations.AlterField(
            model_name='operandintervalrule',
            name='operand_interval_rule_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='间隔规则ID'),
        ),
    ]
