# Generated by Django 4.0 on 2022-05-03 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instruction',
        ),
    ]
