# Generated by Django 4.0 on 2022-03-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buessinessform',
            name='managed_entities',
        ),
    ]
