# Generated by Django 4.0 on 2022-10-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='external_services',
            field=models.ManyToManyField(blank=True, to='define_operand.ExternalServiceMapping', verbose_name='包含的外部服务映射'),
        ),
        migrations.AlterField(
            model_name='project',
            name='service_packages',
            field=models.ManyToManyField(blank=True, to='define_operand.ServicePackage', verbose_name='包含的服务包'),
        ),
        migrations.AlterField(
            model_name='project',
            name='service_rules',
            field=models.ManyToManyField(blank=True, to='define_operand.ServiceRule', verbose_name='包含的服务规则'),
        ),
        migrations.AlterField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(blank=True, to='define_operand.Service', verbose_name='包含的服务'),
        ),
    ]
