# Generated by Django 4.0 on 2022-05-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buessinessformssetting',
            options={'ordering': ['id'], 'verbose_name': '服务表单设置', 'verbose_name_plural': '服务表单设置'},
        ),
        migrations.AlterModelOptions(
            name='managedentity',
            options={'verbose_name': '管理实体', 'verbose_name_plural': '管理实体'},
        ),
    ]
