# Generated by Django 4.0 on 2022-05-13 07:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='managedentity',
            managers=[
                ('entities', django.db.models.manager.Manager()),
            ],
        ),
    ]
