# Generated by Django 4.0 on 2022-03-06 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0002_delete_designbackup_delete_sourcecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='显示名称')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='服务事件名')),
                ('expression', models.TextField(blank=True, default='completed', help_text='\n        说明：<br>\n        1. 作业完成事件: completed<br>\n        2. 表达式接受的逻辑运算符：or, and, not, in, >=, <=, >, <, ==, +, -, *, /, ^, ()<br>\n        3. 字段名只允许由小写字母a~z，数字0~9和下划线_组成；字段值接受数字和字符，字符需要放在双引号中，如"A0101"\n        ', max_length=1024, null=True, verbose_name='表达式')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='事件描述')),
                ('service_event_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='服务事件ID')),
            ],
            options={
                'verbose_name': '服务事件',
                'verbose_name_plural': '服务事件',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['id'], 'verbose_name': '作业事件', 'verbose_name_plural': '作业事件'},
        ),
        migrations.AlterModelOptions(
            name='event_instructions',
            options={'ordering': ['event', 'order'], 'verbose_name': '作业事件指令集', 'verbose_name_plural': '作业事件指令集'},
        ),
        migrations.AlterModelOptions(
            name='eventroute',
            options={'ordering': ['id'], 'verbose_name': '作业事件路由', 'verbose_name_plural': '作业事件路由'},
        ),
        migrations.AlterModelOptions(
            name='operandintervalrule',
            options={'ordering': ['id'], 'verbose_name': '作业间隔规则', 'verbose_name_plural': '作业间隔规则'},
        ),
        migrations.AddField(
            model_name='service',
            name='last_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_operation', to='define_operand.operation', verbose_name='完成作业'),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='last_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_service', to='define_operand.service', verbose_name='结束服务'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='作业事件ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='作业事件名'),
        ),
        migrations.CreateModel(
            name='ServiceEventRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_specified', models.BooleanField(default=False, verbose_name='规定服务')),
                ('service_event_route_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='服务事件路由ID')),
                ('interval_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.operandintervalrule', verbose_name='间隔规则')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='define_operand.service', verbose_name='后续服务')),
                ('service_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='define_operand.serviceevent', verbose_name='服务事件')),
            ],
            options={
                'verbose_name': '服务事件路由',
                'verbose_name_plural': '服务事件路由',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='next_services',
            field=models.ManyToManyField(through='define_operand.ServiceEventRoute', to='define_operand.Service', verbose_name='后续服务'),
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_oid', to='define_operand.service', verbose_name='所属服务'),
        ),
    ]
