# Generated by Django 4.0 on 2022-03-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0002_alter_buessinessform_managed_entities_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['id'], 'verbose_name': '服务', 'verbose_name_plural': '服务'},
        ),
    ]
