# Generated by Django 4.0 on 2023-08-11 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0002_service_arrange_service_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='arrange_service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='define_operand.service', verbose_name='安排服务'),
        ),
    ]
