# Generated by Django 4.0 on 2022-06-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0002_rename_extenalservicefieldsmapping_externalservicefieldsmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepackage',
            name='awaiting_time_frame',
        ),
        migrations.RemoveField(
            model_name='servicepackage',
            name='begin_time_setting',
        ),
        migrations.RemoveField(
            model_name='servicepackage',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='servicepackagedetail',
            name='check_awaiting_timeout',
        ),
        migrations.RemoveField(
            model_name='servicepackagedetail',
            name='reference_start_tim',
        ),
        migrations.AddField(
            model_name='servicepackagedetail',
            name='default_beginning_time',
            field=models.PositiveSmallIntegerField(choices=[(0, '无'), (1, '当前系统时间'), (2, '客户出生日期'), (3, '上个服务结束时间')], default=0, verbose_name='缺省开始时间'),
        ),
    ]
