# Generated by Django 4.0 on 2022-03-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0002_alter_servicepackage_begin_time_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicessetting',
            name='reference_start_tim',
            field=models.DurationField(blank=True, null=True, verbose_name='参考起始时间'),
        ),
    ]
