# Generated by Django 4.0 on 2022-03-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0002_operation_excute_datetime_service_excute_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepackage',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='excute_datetime',
            field=models.DurationField(blank=True, null=True, verbose_name='执行时间'),
        ),
    ]
