# Generated by Django 4.0 on 2023-05-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0002_buessinessform_form_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcomponentssetting',
            name='default_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='默认值'),
        ),
    ]
