# Generated by Django 4.0 on 2022-05-14 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0002_alter_managedentity_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buessinessform',
            name='meta_data',
        ),
    ]
