# Generated by Django 4.0 on 2022-03-27 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0002_remove_buessinessform_managed_entities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managedentity',
            old_name='base_from',
            new_name='base_form',
        ),
    ]
