# Generated by Django 4.0 on 2022-03-11 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0002_buessinessform_alter_systemoperand_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buessinessform',
            old_name='managed_entity',
            new_name='managed_entities',
        ),
    ]
