# Generated by Django 4.0 on 2022-05-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0002_delete_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_system_service',
            field=models.BooleanField(default=False, verbose_name='是否系统作业'),
        ),
    ]
