# Generated by Django 4.0 on 2022-02-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0002_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='label',
            field=models.CharField(default='系统服务', max_length=255, verbose_name='显示名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='角色名'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='名称'),
        ),
    ]
