# Generated by Django 4.0 on 2022-05-29 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0003_rename_medcine_medicine_and_more'),
        ('define_operand', '0002_alter_buessinessformssetting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcomponentssetting',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='define.component', verbose_name='字段'),
        ),
    ]
