# Generated by Django 4.0 on 2022-05-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0002_alter_eventrule_detection_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerule',
            name='route_to',
            field=models.CharField(blank=True, choices=[('/clinic/', '任务工作台'), ('/clinic/customer_service/id/', '客户病例首页')], max_length=255, null=True, verbose_name='跳转至'),
        ),
    ]
