# Generated by Django 4.0 on 2023-03-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0002_service_follow_up_interval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='模型名')),
            ],
            options={
                'verbose_name': '内核模型',
                'verbose_name_plural': '内核模型',
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='follow_up_required',
            field=models.BooleanField(default=False, verbose_name='需要随访'),
        ),
    ]
