# Generated by Django 4.0 on 2022-03-05 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0002_remove_event_next'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventroute',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='define_operand.operation', verbose_name='后续作业'),
        ),
    ]
