# Generated by Django 4.0 on 2022-03-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0002_alter_servicepackagedetail_reference_start_tim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepackagedetail',
            name='reference_start_tim',
            field=models.DurationField(blank=True, default='0 days, 00:00:00', help_text='例如：3 days, 22:00:00', null=True, verbose_name='参考起始时间'),
        ),
    ]
