# Generated by Django 4.0 on 2022-02-03 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_form', '0002_alter_basemodel_managed_entity'),
        ('define_operand', '0002_event_instruction_operation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='forms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_form.combineform', verbose_name='组合视图'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='作业名称'),
        ),
    ]
