# Generated by Django 4.0 on 2022-03-21 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0001_initial'),
        ('define_operand', '0002_service_begin_time_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='first_operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_operation', to='define_operand.operation', verbose_name='起始作业'),
        ),
        migrations.AlterField(
            model_name='service',
            name='group',
            field=models.ManyToManyField(to='define.Role', verbose_name='服务角色'),
        ),
    ]
