# Generated by Django 4.0 on 2022-11-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0001_initial'),
        ('define_operand', '0002_project_external_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='roles',
            field=models.ManyToManyField(blank=True, to='define.Role', verbose_name='项目角色'),
        ),
    ]
