# Generated by Django 4.0 on 2022-03-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0002_remove_serviceevent_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepackageevent',
            name='service',
        ),
    ]
