# Generated by Django 4.0 on 2022-10-22 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0002_service_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='is_system_service',
        ),
    ]
