# Generated by Django 4.0 on 2022-03-09 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0002_buessinessrule_serviceoperations_next_operation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoperations',
            name='interval_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.intervalrule', verbose_name='间隔规则'),
        ),
        migrations.AddField(
            model_name='serviceoperations',
            name='is_specified',
            field=models.BooleanField(default=False, verbose_name='规定作业'),
        ),
        migrations.AddField(
            model_name='serviceoperations',
            name='operation_route_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='作业路由ID'),
        ),
        migrations.AddField(
            model_name='serviceoperations',
            name='passing_data',
            field=models.PositiveSmallIntegerField(choices=[(0, '否'), (1, '复制，不可编辑'), (2, '复制，可以编辑')], default=0, verbose_name='复制表单数据'),
        ),
    ]
