# Generated by Django 4.0 on 2022-06-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0003_alter_formcomponentssetting_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='awaiting_time_frame',
            field=models.DurationField(blank=True, null=True, verbose_name='受理时限'),
        ),
    ]
