# Generated by Django 4.0 on 2023-08-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0003_service_arrange_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepackagedetail',
            name='default_beginning_time',
            field=models.PositiveSmallIntegerField(choices=[(0, '指定开始时间'), (1, '当前系统时间'), (2, '首个服务开始时间'), (3, '上个服务结束时间'), (4, '客户出生日期')], default=1, verbose_name='执行时间基准'),
        ),
    ]
