# Generated by Django 4.0 on 2022-03-06 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0003_serviceevent_alter_event_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OperandIntervalRule',
            new_name='IntervalRule',
        ),
        migrations.AlterModelOptions(
            name='intervalrule',
            options={'ordering': ['id'], 'verbose_name': '间隔规则', 'verbose_name_plural': '间隔规则'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['id'], 'verbose_name': '服务', 'verbose_name_plural': '服务'},
        ),
    ]
