# Generated by Django 4.0 on 2022-03-07 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0003_remove_servicepackageevent_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='history_services_display',
            field=models.PositiveBigIntegerField(choices=[(0, '所有历史服务'), (1, '当日服务')], default=0, verbose_name='历史服务'),
        ),
        migrations.AlterField(
            model_name='service',
            name='enable_queue_counter',
            field=models.BooleanField(default=True, verbose_name='队列计数'),
        ),
        migrations.AlterField(
            model_name='servicepackageevent',
            name='next_servicepackages',
            field=models.ManyToManyField(through='define_operand.ServicePackageEventRoute', to='define_operand.ServicePackage', verbose_name='后续服务'),
        ),
        migrations.AlterField(
            model_name='servicepackageeventroute',
            name='is_specified',
            field=models.BooleanField(default=False, verbose_name='规定服务'),
        ),
        migrations.AlterField(
            model_name='servicepackageeventroute',
            name='servicepackage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='define_operand.servicepackage', verbose_name='后续服务'),
        ),
    ]
