# Generated by Django 4.0 on 2022-10-28 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0003_eventexpression_char_value_eventexpression_intersect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventexpression',
            name='intersect',
        ),
    ]
