# Generated by Django 4.0 on 2023-04-05 10:53

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0001_initial'),
        ('define_operand', '0003_alter_computecomponentssetting_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computecomponentssetting',
            name='component',
            field=models.ForeignKey(limit_choices_to=models.Q(('formcomponentssetting__form', django.db.models.expressions.F('form'))), on_delete=django.db.models.deletion.CASCADE, to='define.component', verbose_name='字段'),
        ),
    ]
