# Generated by Django 4.0 on 2022-02-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0003_service_label_alter_role_name_alter_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='group',
            field=models.ManyToManyField(to='define_operand.Role', verbose_name='作业角色'),
        ),
    ]
