# Generated by Django 4.0 on 2022-11-08 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0001_initial'),
        ('define_operand', '0003_project_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedentity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='define_operand.project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='project',
            name='external_services',
            field=models.ManyToManyField(blank=True, to='define_operand.ExternalServiceMapping', verbose_name='外部服务映射'),
        ),
        migrations.AlterField(
            model_name='project',
            name='roles',
            field=models.ManyToManyField(blank=True, to='define.Role', verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='project',
            name='service_packages',
            field=models.ManyToManyField(blank=True, to='define_operand.ServicePackage', verbose_name='服务包'),
        ),
        migrations.AlterField(
            model_name='project',
            name='service_rules',
            field=models.ManyToManyField(blank=True, to='define_operand.ServiceRule', verbose_name='服务规则'),
        ),
        migrations.AlterField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(blank=True, to='define_operand.Service', verbose_name='服务'),
        ),
    ]
