# Generated by Django 4.0 on 2022-03-25 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_rule_dict', '0002_servicespec'),
        ('define_operand', '0003_servicessetting_reference_start_tim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicessetting',
            name='check_awaiting_timeout',
        ),
        migrations.RemoveField(
            model_name='servicessetting',
            name='servicepackage',
        ),
        migrations.AddField(
            model_name='servicessetting',
            name='service_spec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='define_rule_dict.servicespec', verbose_name='服务规格'),
        ),
        migrations.AlterField(
            model_name='servicessetting',
            name='reference_start_tim',
            field=models.DurationField(blank=True, help_text='例如：3 days, 22:00:00', null=True, verbose_name='参考起始时间'),
        ),
        migrations.CreateModel(
            name='ServicePackageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('cycle_option', models.PositiveSmallIntegerField(blank=True, choices=[(0, '总共'), (1, '每天'), (2, '每周'), (3, '每月'), (4, '每季'), (5, '每年')], default=0, null=True, verbose_name='周期')),
                ('cycle_times', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='次数')),
                ('reference_start_tim', models.DurationField(blank=True, help_text='例如：3 days, 22:00:00', null=True, verbose_name='参考起始时间')),
                ('duration', models.DurationField(blank=True, help_text='例如：3 days, 22:00:00', null=True, verbose_name='持续周期')),
                ('check_awaiting_timeout', models.BooleanField(default=False, verbose_name='检查等待超时')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.service', verbose_name='服务项目')),
                ('servicepackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='define_operand.servicepackage', verbose_name='服务包')),
            ],
            options={
                'verbose_name': '服务内容模板',
                'verbose_name_plural': '服务内容模板',
                'ordering': ['id'],
            },
        ),
    ]
