# Generated by Django 4.0 on 2022-02-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0003_alter_operation_forms_alter_operation_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OperandView',
        ),
    ]
