# Generated by Django 4.0 on 2022-03-14 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_rule_dict', '0002_alter_eventrule_options_alter_eventexpression_label_and_more'),
        ('define_operand', '0003_event_instruction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicessetting',
            name='next_service_confirmation_required',
        ),
        migrations.AddField(
            model_name='servicessetting',
            name='accepting_confirm',
            field=models.BooleanField(default=False, verbose_name='接受确认'),
        ),
        migrations.AlterField(
            model_name='buessinessform',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='formentityship',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='operationssetting',
            name='event_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='define_rule_dict.eventrule', verbose_name='条件事件'),
        ),
        migrations.AlterField(
            model_name='operationssetting',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='role',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='servicessetting',
            name='event_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_rule_dict.eventrule', verbose_name='条件事件'),
        ),
        migrations.AlterField(
            model_name='servicessetting',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='systemoperand',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
    ]
