# Generated by Django 4.0 on 2022-05-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0003_servicerule_route_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerule',
            name='route_to',
        ),
        migrations.AddField(
            model_name='service',
            name='route_to',
            field=models.CharField(blank=True, choices=[('INDEX', '任务工作台'), ('CUSTOMER_HOMEPAGE', '客户病例首页')], max_length=255, null=True, verbose_name='跳转至'),
        ),
    ]
