# Generated by Django 4.0 on 2022-05-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0003_remove_buessinessform_meta_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buessinessform',
            name='script',
        ),
        migrations.RemoveField(
            model_name='service',
            name='script',
        ),
    ]
