# Generated by Django 4.0 on 2022-05-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0003_service_is_system_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='is_system_service',
            field=models.BooleanField(default=False, verbose_name='系统内置服务'),
        ),
    ]
