# Generated by Django 4.0 on 2022-03-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0003_remove_servicessetting_accepting_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicessetting',
            name='message_content',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='消息内容'),
        ),
        migrations.AddField(
            model_name='servicessetting',
            name='reminders',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '当前客户'), (1, '当前服务人员'), (2, '当前服务小组')], default=0, null=True, verbose_name='提醒对象'),
        ),
    ]
