# Generated by Django 4.0 on 2022-03-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0003_remove_servicepackage_start_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='excute_datetime',
        ),
        migrations.RemoveField(
            model_name='service',
            name='excute_datetime',
        ),
        migrations.RemoveField(
            model_name='servicepackage',
            name='excute_datetime',
        ),
        migrations.AddField(
            model_name='operation',
            name='execute_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='执行时间'),
        ),
        migrations.AddField(
            model_name='service',
            name='execute_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='执行时间'),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='execute_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='执行时间'),
        ),
    ]
