# Generated by Django 4.0 on 2023-06-14 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0001_initial'),
        ('define_operand', '0003_formcomponentssetting_default_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormListComponentsSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('default_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='默认值')),
                ('is_required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('position', models.PositiveSmallIntegerField(default=100, verbose_name='位置顺序')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='define.component', verbose_name='字段')),
            ],
            options={
                'verbose_name': '表单列表字段设置',
                'verbose_name_plural': '表单列表字段设置',
            },
        ),
        migrations.AlterModelOptions(
            name='formcomponentssetting',
            options={'verbose_name': '表单字段设置', 'verbose_name_plural': '表单字段设置'},
        ),
        migrations.AddField(
            model_name='buessinessform',
            name='list_components',
            field=models.ManyToManyField(related_name='list_components_in_forms', through='define_operand.FormListComponentsSetting', to='define.Component', verbose_name='列表字段'),
        ),
        migrations.AlterField(
            model_name='buessinessform',
            name='components',
            field=models.ManyToManyField(related_name='components_in_forms', through='define_operand.FormComponentsSetting', to='define.Component', verbose_name='字段'),
        ),
        migrations.AddField(
            model_name='formlistcomponentssetting',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='define_operand.buessinessform', verbose_name='表单'),
        ),
    ]
