# Generated by Django 4.0 on 2022-03-09 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0003_serviceoperations_interval_rule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoperations',
            name='buessiness_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.buessinessrule', verbose_name='内容检查'),
        ),
        migrations.AlterField(
            model_name='serviceoperations',
            name='interval_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.intervalrule', verbose_name='时间间隔'),
        ),
    ]
