# Generated by Django 4.0 on 2022-06-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0003_remove_servicepackage_awaiting_time_frame_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackagedetail',
            name='base_interval',
            field=models.DurationField(blank=True, help_text='例如：3 days, 22:00:00', null=True, verbose_name='基准间隔'),
        ),
        migrations.AlterField(
            model_name='servicepackagedetail',
            name='default_beginning_time',
            field=models.PositiveSmallIntegerField(choices=[(0, '无'), (1, '当前系统时间'), (2, '首个服务开始时间'), (3, '上个服务结束时间'), (4, '客户出生日期')], default=0, verbose_name='执行时间基准'),
        ),
    ]
