# Generated by Django 4.0 on 2023-09-09 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0004_alter_servicepackagedetail_default_beginning_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemOperandParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('parameter1', models.CharField(blank=True, max_length=255, null=True, verbose_name='系统参数1')),
                ('form_field1', models.CharField(blank=True, max_length=255, null=True, verbose_name='对应字段1')),
                ('parameter2', models.CharField(blank=True, max_length=255, null=True, verbose_name='系统参数2')),
                ('form_field2', models.CharField(blank=True, max_length=255, null=True, verbose_name='对应字段2')),
                ('parameter3', models.CharField(blank=True, max_length=255, null=True, verbose_name='系统参数3')),
                ('form_field3', models.CharField(blank=True, max_length=255, null=True, verbose_name='对应字段3')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='说明')),
                ('system_operand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='define_operand.systemoperand', verbose_name='系统作业')),
            ],
            options={
                'verbose_name': '系统作业参数表',
                'verbose_name_plural': '系统作业参数表',
                'ordering': ['id'],
            },
        ),
    ]
