# Generated by Django 4.0 on 2022-06-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0004_servicepackagedetail_base_interval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='awaiting_time_frame',
        ),
        migrations.RemoveField(
            model_name='service',
            name='execution_time_frame',
        ),
        migrations.RemoveField(
            model_name='servicepackage',
            name='execution_time_frame',
        ),
        migrations.AddField(
            model_name='service',
            name='overtime',
            field=models.DurationField(blank=True, null=True, verbose_name='超期时限'),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='overtime',
            field=models.DurationField(blank=True, null=True, verbose_name='超期时限'),
        ),
    ]
