# Generated by Django 4.0 on 2022-10-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0004_remove_eventexpression_intersect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventexpression',
            name='value',
        ),
    ]
