# Generated by Django 4.0 on 2022-03-25 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0004_remove_servicessetting_check_awaiting_timeout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepackage',
            name='first_service',
        ),
        migrations.RemoveField(
            model_name='servicepackage',
            name='last_service',
        ),
    ]
