# Generated by Django 4.0 on 2023-06-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0004_formlistcomponentssetting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buessinessform',
            name='form_style',
        ),
    ]
