# Generated by Django 4.0 on 2022-03-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0004_remove_servicessetting_next_service_confirmation_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicessetting',
            name='complete_feedback',
            field=models.BooleanField(default=False, verbose_name='完成反馈'),
        ),
    ]
