# Generated by Django 4.0 on 2022-03-06 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0004_rename_operandintervalrule_intervalrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceevent',
            name='fields',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='可用字段'),
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.operation', verbose_name='所属作业'),
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='parameters',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='检查字段'),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_sid', to='define_operand.service', verbose_name='所属服务'),
        ),
    ]
