# Generated by Django 4.0 on 2022-05-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0004_remove_servicerule_route_to_service_route_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='route_to',
            field=models.CharField(blank=True, choices=[('INDEX', '任务工作台'), ('CUSTOMER_HOMEPAGE', '客户病例首页')], default='INDEX', max_length=50, null=True, verbose_name='跳转至'),
        ),
    ]
