# Generated by Django 4.0 on 2022-06-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0004_alter_service_awaiting_time_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='awaiting_time_frame',
            field=models.DurationField(blank=True, help_text='示例: 1d 2:00:00', null=True, verbose_name='受理时限'),
        ),
    ]
