# Generated by Django 4.0 on 2022-03-09 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0004_alter_serviceoperations_buessiness_rule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='history_services_display',
            field=models.PositiveBigIntegerField(choices=[(0, '所有历史服务'), (1, '当日服务')], default=0, null=True, verbose_name='历史服务默认显示'),
        ),
        migrations.AlterField(
            model_name='serviceoperations',
            name='buessiness_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.buessinessrule', verbose_name='事件规则'),
        ),
    ]
