# Generated by Django 4.0 on 2022-03-07 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0001_initial'),
        ('define_operand', '0004_service_history_services_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='managed_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define.managedentity', verbose_name='管理实体'),
        ),
        migrations.AlterField(
            model_name='service',
            name='enable_queue_counter',
            field=models.BooleanField(default=True, verbose_name='显示队列计数'),
        ),
        migrations.AlterField(
            model_name='service',
            name='history_services_display',
            field=models.PositiveBigIntegerField(choices=[(0, '所有历史服务'), (1, '当日服务')], default=0, verbose_name='历史服务显示'),
        ),
    ]
