# Generated by Django 4.0 on 2022-03-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_rule_dict', '0002_servicespec'),
        ('define_operand', '0005_remove_servicepackage_first_service_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicesSetting',
            new_name='ServiceProgramSetting',
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='begin_time_setting',
            field=models.PositiveSmallIntegerField(choices=[(0, '人工指定'), (1, '出生日期')], default=0, verbose_name='开始时间参考'),
        ),
    ]
