# Generated by Django 4.0 on 2023-05-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0005_remove_computecomponentssetting_js_script_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrule',
            name='event_type',
            field=models.CharField(choices=[('FORM_EVENT', '表单事件'), ('SCHEDULE_EVENT', '调度事件')], default='SCHEDULE_EVENT', max_length=100, verbose_name='事件类型'),
        ),
    ]
