# Generated by Django 4.0 on 2023-09-09 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0005_systemoperandparameter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemoperandparameter',
            options={'ordering': ['id'], 'verbose_name': '系统自动作业参数', 'verbose_name_plural': '系统自动作业参数'},
        ),
        migrations.RemoveField(
            model_name='systemoperandparameter',
            name='system_operand',
        ),
        migrations.AddField(
            model_name='servicerule',
            name='system_operand_parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.systemoperandparameter', verbose_name='系统作业参数'),
        ),
        migrations.AlterField(
            model_name='systemoperandparameter',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='说明'),
        ),
    ]
