# Generated by Django 4.0 on 2022-03-07 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0005_serviceevent_fields_serviceevent_operation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='显示名称')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='服务包事件名')),
                ('expression', models.TextField(blank=True, default='completed', help_text='\n        说明：<br>\n        1. 作业完成事件: completed<br>\n        2. 表达式接受的逻辑运算符：or, and, not, in, >=, <=, >, <, ==, +, -, *, /, ^, ()<br>\n        3. 字段名只允许由小写字母a~z，数字0~9和下划线_组成；字段值接受数字和字符，字符需要放在双引号中，如"A0101"\n        ', max_length=1024, null=True, verbose_name='表达式')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='事件描述')),
                ('servicepackage_event_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='服务包事件ID')),
            ],
            options={
                'verbose_name': '服务包事件',
                'verbose_name_plural': '服务包事件',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_service_id', to='define_operand.service', verbose_name='所属服务'),
        ),
        migrations.CreateModel(
            name='ServicePackageEventRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_specified', models.BooleanField(default=False, verbose_name='规定服务包')),
                ('servicepackage_event_route_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='服务包事件路由ID')),
                ('interval_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.intervalrule', verbose_name='间隔规则')),
                ('servicepackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='define_operand.servicepackage', verbose_name='后续服务包')),
                ('servicepackage_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='define_operand.servicepackageevent', verbose_name='服务包事件')),
            ],
            options={
                'verbose_name': '服务包事件路由',
                'verbose_name_plural': '服务包事件路由',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='servicepackageevent',
            name='next_servicepackages',
            field=models.ManyToManyField(through='define_operand.ServicePackageEventRoute', to='define_operand.ServicePackage', verbose_name='后续服务包'),
        ),
        migrations.AddField(
            model_name='servicepackageevent',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_servicepackage_id', to='define_operand.service', verbose_name='所属服务'),
        ),
        migrations.AddField(
            model_name='servicepackageevent',
            name='servicepackage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_sid', to='define_operand.servicepackage', verbose_name='所属服务包'),
        ),
    ]
