# Generated by Django 4.0 on 2022-06-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0005_remove_service_awaiting_time_frame_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedentity',
            name='header_fields_json',
            field=models.JSONField(blank=True, null=True, verbose_name='表头字段json'),
        ),
    ]
