# Generated by Django 4.0 on 2022-06-04 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0005_alter_service_awaiting_time_frame'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='managedentity',
            managers=[
            ],
        ),
    ]
