# Generated by Django 4.0 on 2022-03-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0005_service_managed_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='enable_recommanded_list',
            field=models.BooleanField(default=True, verbose_name='显示推荐作业'),
        ),
    ]
