# Generated by Django 4.0 on 2022-03-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0005_servicessetting_complete_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationssetting',
            name='operations_setting_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_id',
        ),
        migrations.AddField(
            model_name='buessinessform',
            name='pym',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码'),
        ),
        migrations.AddField(
            model_name='operation',
            name='pym',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码'),
        ),
        migrations.AddField(
            model_name='service',
            name='pym',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码'),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='pym',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码'),
        ),
    ]
