# Generated by Django 4.0 on 2022-02-20 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0005_alter_service_first_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='成本'),
        ),
        migrations.AddField(
            model_name='service',
            name='frequency',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='频次'),
        ),
        migrations.AddField(
            model_name='service',
            name='group',
            field=models.ManyToManyField(blank=True, to='define_operand.Role', verbose_name='服务角色'),
        ),
        migrations.AddField(
            model_name='service',
            name='load_feedback',
            field=models.BooleanField(default=False, verbose_name='是否反馈负荷数量'),
        ),
        migrations.AddField(
            model_name='service',
            name='not_suitable',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='不适用对象'),
        ),
        migrations.AddField(
            model_name='service',
            name='operations',
            field=models.ManyToManyField(blank=True, to='define_operand.Operation', verbose_name='包含作业'),
        ),
        migrations.AddField(
            model_name='service',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, '0级'), (1, '紧急'), (2, '优先'), (3, '一般')], default=3, verbose_name='优先级'),
        ),
        migrations.AddField(
            model_name='service',
            name='resource_devices',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='配套设备'),
        ),
        migrations.AddField(
            model_name='service',
            name='resource_knowledge',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='服务知识'),
        ),
        migrations.AddField(
            model_name='service',
            name='resource_materials',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='配套物料'),
        ),
        migrations.AddField(
            model_name='service',
            name='suppliers',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='供应商'),
        ),
        migrations.AddField(
            model_name='service',
            name='time_limits',
            field=models.DurationField(blank=True, null=True, verbose_name='完成时限'),
        ),
        migrations.AddField(
            model_name='service',
            name='working_hours',
            field=models.DurationField(blank=True, null=True, verbose_name='工时'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='group',
            field=models.ManyToManyField(blank=True, to='define_operand.Role', verbose_name='作业角色'),
        ),
        migrations.AlterField(
            model_name='service',
            name='first_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_operation', to='define_operand.operation', verbose_name='起始作业'),
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名称')),
                ('label', models.CharField(max_length=255, verbose_name='显示名称')),
                ('first_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_service', to='define_operand.service', verbose_name='起始作业')),
                ('services', models.ManyToManyField(blank=True, to='define_operand.Service', verbose_name='包含服务')),
            ],
            options={
                'verbose_name': '服务包',
                'verbose_name_plural': '服务包',
                'ordering': ['id'],
            },
        ),
    ]
