# Generated by Django 4.0 on 2023-07-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0005_remove_buessinessform_form_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='域名'),
        ),
    ]
