# Generated by Django 4.0 on 2022-03-09 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0005_alter_service_history_services_display_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('system_action_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='系统动作ID')),
            ],
            options={
                'verbose_name': '系统动作',
                'verbose_name_plural': '系统动作',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='buessinessrule',
            options={'ordering': ['id'], 'verbose_name': '业务规则', 'verbose_name_plural': '业务规则'},
        ),
        migrations.AlterField(
            model_name='service',
            name='history_services_display',
            field=models.PositiveBigIntegerField(blank=True, choices=[(0, '所有历史服务'), (1, '当日服务')], default=0, null=True, verbose_name='历史服务默认显示'),
        ),
        migrations.AddField(
            model_name='serviceoperations',
            name='system_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.systemaction', verbose_name='系统动作'),
        ),
    ]
