# Generated by Django 4.0 on 2022-06-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0006_alter_managedentity_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcomponentssetting',
            name='api_field',
            field=models.CharField(blank=True, choices=[('charge_staff', '责任人'), ('operator', '作业人员'), ('scheduled_time', '计划执行时间')], max_length=50, null=True, verbose_name='对接系统接口'),
        ),
    ]
