# Generated by Django 4.0 on 2022-03-09 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0006_systemaction_alter_buessinessrule_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceoperations',
            name='is_specified',
        ),
        migrations.AddField(
            model_name='systemaction',
            name='func',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='内部实现函数'),
        ),
        migrations.AddField(
            model_name='systemaction',
            name='parameters',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='参数'),
        ),
        migrations.AlterField(
            model_name='serviceoperations',
            name='interval_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.intervalrule', verbose_name='时间间隔限制'),
        ),
        migrations.AlterField(
            model_name='serviceoperations',
            name='passing_data',
            field=models.PositiveSmallIntegerField(choices=[(0, '否'), (1, '复制，不可编辑'), (2, '复制，可以编辑')], default=0, verbose_name='传递表单数据'),
        ),
    ]
