# Generated by Django 4.0 on 2023-07-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0006_project_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='formlistcomponentssetting',
            name='autofill_fields',
            field=models.BooleanField(default=False, verbose_name='自动填充'),
        ),
    ]
