# Generated by Django 4.0 on 2022-02-20 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0006_service_cost_service_frequency_service_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepackage',
            name='first_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_service', to='define_operand.service', verbose_name='起始服务'),
        ),
    ]
