# Generated by Django 4.0 on 2022-03-25 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0006_rename_servicessetting_serviceprogramsetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
            ],
            options={
                'verbose_name': '服务规格',
                'verbose_name_plural': '服务规格',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='serviceprogramsetting',
            name='cycle_option',
        ),
        migrations.RemoveField(
            model_name='serviceprogramsetting',
            name='cycle_times',
        ),
        migrations.RemoveField(
            model_name='serviceprogramsetting',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='serviceprogramsetting',
            name='reference_start_tim',
        ),
        migrations.AlterField(
            model_name='serviceprogramsetting',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.service', verbose_name='服务项目'),
        ),
        migrations.AlterField(
            model_name='serviceprogramsetting',
            name='service_spec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.servicespec', verbose_name='服务规格'),
        ),
    ]
