# Generated by Django 4.0 on 2022-06-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0006_managedentity_header_fields_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepackagedetail',
            name='cycle_option',
        ),
        migrations.RemoveField(
            model_name='servicepackagedetail',
            name='duration',
        ),
        migrations.AddField(
            model_name='servicepackagedetail',
            name='cycle_frequency',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='每周期频次'),
        ),
        migrations.AddField(
            model_name='servicepackagedetail',
            name='cycle_unit',
            field=models.CharField(blank=True, choices=[('TOTAL', '总共'), ('DAY', '每天'), ('WEEK', '每周'), ('MONTH', '每月'), ('QUARTER', '每季'), ('YEAR', '每年')], default='TOTAL', max_length=10, null=True, verbose_name='周期单位'),
        ),
        migrations.AlterField(
            model_name='servicepackagedetail',
            name='cycle_times',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='周期数/天数'),
        ),
    ]
