# Generated by Django 4.0 on 2023-09-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0006_alter_systemoperandparameter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemoperandparameter',
            name='form_field1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='对应业务字段1'),
        ),
        migrations.AlterField(
            model_name='systemoperandparameter',
            name='form_field2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='对应业务字段2'),
        ),
        migrations.AlterField(
            model_name='systemoperandparameter',
            name='form_field3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='对应业务字段3'),
        ),
    ]
