# Generated by Django 4.0 on 2023-09-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0007_alter_systemoperandparameter_form_field1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerule',
            name='system_operand_parameter',
        ),
        migrations.AddField(
            model_name='servicerule',
            name='detect_record_range',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '单条记录'), (1, '分组记录')], default=0, verbose_name='检测记录范围'),
        ),
    ]
