# Generated by Django 4.0 on 2022-06-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0007_formcomponentssetting_api_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='buessinessform',
            name='api_fields',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='API字段'),
        ),
    ]
