# Generated by Django 4.0 on 2022-02-23 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_icpc', '0006_icpc'),
        ('define_operand', '0007_alter_servicepackage_first_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='name_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_icpc.icpc', verbose_name='作业ICPC'),
        ),
    ]
