# Generated by Django 4.0 on 2022-03-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0007_servicespec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='services',
            field=models.ManyToManyField(null=True, through='define_operand.ServicePackageDetail', to='define_operand.Service', verbose_name='服务项目'),
        ),
    ]
