# Generated by Django 4.0 on 2022-03-09 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0007_remove_serviceoperations_is_specified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOperationsShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passing_data', models.PositiveSmallIntegerField(choices=[(0, '否'), (1, '复制，不可编辑'), (2, '复制，可以编辑')], default=0, verbose_name='传递表单数据')),
                ('service_operations_ship_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='作业路由ID')),
            ],
            options={
                'verbose_name': '作业关系设置',
                'verbose_name_plural': '作业关系设置',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='service',
            name='operations',
        ),
        migrations.AlterField(
            model_name='buessinessrule',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.DeleteModel(
            name='ServiceOperations',
        ),
        migrations.AddField(
            model_name='serviceoperationsship',
            name='buessiness_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.buessinessrule', verbose_name='事件规则'),
        ),
        migrations.AddField(
            model_name='serviceoperationsship',
            name='interval_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.intervalrule', verbose_name='时间间隔限制'),
        ),
        migrations.AddField(
            model_name='serviceoperationsship',
            name='next_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_operation', to='define_operand.operation', verbose_name='后续作业'),
        ),
        migrations.AddField(
            model_name='serviceoperationsship',
            name='operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation', to='define_operand.operation', verbose_name='作业'),
        ),
        migrations.AddField(
            model_name='serviceoperationsship',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='define_operand.service', verbose_name='单元服务'),
        ),
        migrations.AddField(
            model_name='serviceoperationsship',
            name='system_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.systemaction', verbose_name='系统动作'),
        ),
    ]
