# Generated by Django 4.0 on 2022-06-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0007_remove_servicepackagedetail_cycle_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepackagedetail',
            name='default_beginning_time',
            field=models.PositiveSmallIntegerField(choices=[(1, '当前系统时间'), (2, '首个服务开始时间'), (3, '上个服务结束时间'), (4, '客户出生日期')], default=1, verbose_name='执行时间基准'),
        ),
    ]
