# Generated by Django 4.0 on 2022-03-25 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0008_servicepackage_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicespec',
            options={'ordering': ['id'], 'verbose_name': '服务关系设置', 'verbose_name_plural': '服务关系设置'},
        ),
    ]
