# Generated by Django 4.0 on 2022-08-15 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0008_alter_servicepackagedetail_default_beginning_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemoperand',
            name='applicable',
        ),
        migrations.AlterField(
            model_name='servicerule',
            name='system_operand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.systemoperand', verbose_name='系统作业'),
        ),
    ]
