# Generated by Django 4.0 on 2022-03-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0008_alter_event_label_alter_event_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventroute',
            name='passing_data',
            field=models.PositiveSmallIntegerField(choices=[(0, '否'), (1, '继承内容，不可编辑'), (2, '继承内容，可以编辑')], default=0, verbose_name='复制表单数据'),
        ),
        migrations.AddField(
            model_name='serviceeventroute',
            name='passing_data',
            field=models.PositiveSmallIntegerField(choices=[(0, '否'), (1, '继承内容，不可编辑'), (2, '继承内容，可以编辑')], default=0, verbose_name='复制表单数据'),
        ),
    ]
