# Generated by Django 4.0 on 2023-09-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0008_remove_servicerule_system_operand_parameter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerule',
            name='detect_record_range',
        ),
        migrations.AddField(
            model_name='servicerule',
            name='apply_to_group',
            field=models.BooleanField(choices=[(False, '否'), (True, '是')], default=False, verbose_name='应用于分组'),
        ),
    ]
