# Generated by Django 4.0 on 2022-02-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_icpc', '0006_icpc'),
        ('define_operand', '0008_operation_name_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='name_new',
        ),
        migrations.AddField(
            model_name='operation',
            name='name_new',
            field=models.ManyToManyField(to='define_icpc.Icpc', verbose_name='作业ICPC'),
        ),
    ]
