# Generated by Django 4.0 on 2022-06-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0008_buessinessform_api_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buessinessform',
            name='api_fields',
            field=models.JSONField(blank=True, null=True, verbose_name='API字段'),
        ),
    ]
