# Generated by Django 4.0 on 2023-09-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0009_remove_servicerule_detect_record_range_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formcomponentssetting',
            name='api_field',
        ),
    ]
