# Generated by Django 4.0 on 2022-03-26 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0004_remove_managedentity_content_type_and_more'),
        ('define_operand', '0009_alter_servicespec_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='表达式')),
                ('detection_scope', models.PositiveSmallIntegerField(blank=True, choices=[(0, '所有历史表单'), (1, '本次服务表单'), (2, '单元服务表单')], default=1, null=True, verbose_name='检测范围')),
                ('weight', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='权重')),
                ('expression', models.TextField(blank=True, max_length=1024, null=True, verbose_name='内部表达式')),
            ],
            options={
                'verbose_name': '条件事件',
                'verbose_name_plural': '条件事件',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IntervalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('rule', models.PositiveSmallIntegerField(blank=True, choices=[(0, '等于'), (1, '小于'), (2, '大于')], null=True, verbose_name='间隔规则')),
                ('interval', models.DurationField(blank=True, help_text='例如：3 days, 22:00:00', null=True, verbose_name='间隔时间')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='说明')),
            ],
            options={
                'verbose_name': '间隔规则',
                'verbose_name_plural': '间隔规则',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='serviceprogramsetting',
            options={'ordering': ['id'], 'verbose_name': '服务程序设置', 'verbose_name_plural': '服务程序设置'},
        ),
        migrations.AlterModelOptions(
            name='servicespec',
            options={'ordering': ['id'], 'verbose_name': '服务规格设置', 'verbose_name_plural': '服务规格设置'},
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='services',
            field=models.ManyToManyField(through='define_operand.ServicePackageDetail', to='define_operand.Service', verbose_name='服务项目'),
        ),
        migrations.CreateModel(
            name='EventExpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('operator', models.PositiveSmallIntegerField(choices=[(0, '=='), (1, '!='), (2, '>'), (3, '<'), (4, '>='), (5, '<='), (6, 'in'), (7, 'not in')], null=True, verbose_name='操作符')),
                ('value', models.CharField(help_text='多个值用英文逗号分隔，空格会被忽略', max_length=255, null=True, verbose_name='值')),
                ('connection_operator', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'and'), (1, 'or')], null=True, verbose_name='连接操作符')),
                ('event_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.eventrule', verbose_name='事件规则')),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='define.component', verbose_name='字段')),
            ],
            options={
                'verbose_name': '事件表达式',
                'verbose_name_plural': '事件表达式',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='operationssetting',
            name='event_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.eventrule', verbose_name='条件事件'),
        ),
        migrations.AlterField(
            model_name='operationssetting',
            name='interval_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.intervalrule', verbose_name='时间间隔限制'),
        ),
        migrations.AlterField(
            model_name='serviceprogramsetting',
            name='event_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.eventrule', verbose_name='条件事件'),
        ),
        migrations.AlterField(
            model_name='serviceprogramsetting',
            name='interval_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.intervalrule', verbose_name='服务时间间隔'),
        ),
    ]
