# Generated by Django 4.0 on 2022-03-09 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0009_rename_systemaction_systemoperand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackageServicesShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passing_data', models.PositiveSmallIntegerField(choices=[(0, '否'), (1, '复制，不可编辑'), (2, '复制，可以编辑')], default=0, verbose_name='传递表单数据')),
                ('servicepackage_services_ship_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='服务关系ID')),
                ('buessiness_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.buessinessrule', verbose_name='事件规则')),
                ('interval_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.intervalrule', verbose_name='时间间隔限制')),
                ('next_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_service', to='define_operand.service', verbose_name='后续服务')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.service', verbose_name='单元服务')),
                ('servicepackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='define_operand.servicepackage', verbose_name='服务包')),
                ('system_operand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.systemoperand', verbose_name='系统作业')),
            ],
            options={
                'verbose_name': '服务关系设置',
                'verbose_name_plural': '服务关系设置',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='servicepackageeventroute',
            name='interval_rule',
        ),
        migrations.RemoveField(
            model_name='servicepackageeventroute',
            name='servicepackage',
        ),
        migrations.RemoveField(
            model_name='servicepackageeventroute',
            name='servicepackage_event',
        ),
        migrations.AlterField(
            model_name='serviceoperationsship',
            name='service_operations_ship_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='作业关系ID'),
        ),
        migrations.AlterField(
            model_name='serviceoperationsship',
            name='system_operand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.systemoperand', verbose_name='系统作业'),
        ),
        migrations.DeleteModel(
            name='ServicePackageEvent',
        ),
        migrations.DeleteModel(
            name='ServicePackageEventRoute',
        ),
    ]
