# Generated by Django 4.0 on 2022-06-15 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0006_alter_characterfield_label_alter_characterfield_name_and_more'),
        ('define_operand', '0009_alter_buessinessform_api_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalServiceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('external_form_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='外部表单标识')),
                ('external_form_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='外部表单名称')),
                ('form_source', models.CharField(blank=True, choices=[('jinshuju', '金数据'), ('other', '其它')], max_length=50, null=True, verbose_name='来源名称')),
                ('fields_mapping', models.JSONField(blank=True, null=True, verbose_name='字段映射')),
                ('service', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.service', verbose_name='对应服务')),
            ],
            options={
                'verbose_name': '外部服务映射',
                'verbose_name_plural': '外部服务映射',
            },
        ),
        migrations.CreateModel(
            name='ExtenalServiceFieldsMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('external_field_name', models.CharField(max_length=100, null=True, verbose_name='外部字段名称')),
                ('external_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.externalservicemapping', verbose_name='外部表单')),
                ('service_form_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='define.component', verbose_name='服务表单字段')),
            ],
            options={
                'verbose_name': '外部服务字段映射',
                'verbose_name_plural': '外部服务字段映射',
            },
        ),
    ]
