# Generated by Django 4.0 on 2022-03-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0010_servicepackageservicesship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemoperand',
            name='applicable',
            field=models.PositiveSmallIntegerField(choices=[(0, '作业'), (1, '单元服务'), (2, '服务包'), (3, '全部')], default=1, verbose_name='适用范围'),
        ),
    ]
