# Generated by Django 4.0 on 2023-09-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0010_remove_formcomponentssetting_api_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerule',
            name='apply_to_group',
            field=models.BooleanField(choices=[(False, '否'), (True, '是')], default=False, verbose_name='使用分组'),
        ),
    ]
