# Generated by Django 4.0 on 2022-03-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0010_eventrule_intervalrule_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervalrule',
            old_name='rule',
            new_name='interval_rule',
        ),
        migrations.RenameField(
            model_name='intervalrule',
            old_name='interval',
            new_name='interval_time',
        ),
        migrations.AddField(
            model_name='serviceprogramsetting',
            name='interval_time',
            field=models.DurationField(blank=True, help_text='例如：3 days, 22:00:00', null=True, verbose_name='间隔时间'),
        ),
        migrations.AlterField(
            model_name='serviceprogramsetting',
            name='interval_rule',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '等于'), (1, '小于'), (2, '大于')], null=True, verbose_name='间隔规则'),
        ),
    ]
