# Generated by Django 4.0 on 2022-03-09 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0011_systemoperand_applicable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemoperand',
            options={'ordering': ['id'], 'verbose_name': '系统作业', 'verbose_name_plural': '系统作业'},
        ),
        migrations.RemoveField(
            model_name='servicepackage',
            name='execute_datetime',
        ),
        migrations.RemoveField(
            model_name='servicepackage',
            name='services',
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='first_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_service', to='define_operand.service', verbose_name='起始服务'),
        ),
        migrations.AlterField(
            model_name='servicepackageservicesship',
            name='buessiness_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.buessinessrule', verbose_name='事件规则'),
        ),
        migrations.AlterField(
            model_name='servicepackageservicesship',
            name='passing_data',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '否'), (1, '复制，不可编辑'), (2, '复制，可以编辑')], default=0, null=True, verbose_name='传递表单数据'),
        ),
    ]
