# Generated by Django 4.0 on 2022-03-26 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0011_rename_rule_intervalrule_interval_rule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationssetting',
            name='interval_rule',
        ),
        migrations.DeleteModel(
            name='IntervalRule',
        ),
    ]
