# Generated by Django 4.0 on 2023-09-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0011_alter_servicerule_apply_to_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemOperandParameter',
        ),
    ]
