# Generated by Django 4.0 on 2022-03-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0012_alter_systemoperand_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='duration',
            field=models.DurationField(blank=True, help_text='例如：3 days, 22:00:00', null=True, verbose_name='持续周期'),
        ),
    ]
