# Generated by Django 4.0 on 2023-10-03 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0008_alter_systemreservedfield_type'),
        ('define_operand', '0012_delete_systemoperandparameter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['id'], 'verbose_name': '服务作业', 'verbose_name_plural': '服务作业'},
        ),
        migrations.CreateModel(
            name='L1Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('end_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_service', to='define_operand.service', verbose_name='结束服务项目')),
                ('include_services', models.ManyToManyField(blank=True, related_name='include_services', to='define_operand.Service', verbose_name='包含服务项目')),
                ('role', models.ManyToManyField(blank=True, to='define.Role', verbose_name='服务岗位')),
                ('start_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_service', to='define_operand.service', verbose_name='启示服务项目')),
            ],
            options={
                'verbose_name': '服务任务',
                'verbose_name_plural': '服务任务',
                'ordering': ['id'],
            },
        ),
    ]
