# Generated by Django 4.0 on 2022-03-09 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0013_servicepackage_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequencyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='规则名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='name')),
                ('cycle_option', models.PositiveSmallIntegerField(blank=True, choices=[(0, '天'), (1, '周'), (2, '月'), (3, '季'), (4, '年')], null=True, verbose_name='每周期')),
                ('times', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='次数')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='说明')),
                ('frequency_rule_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='频度规则ID')),
            ],
            options={
                'verbose_name': '频度规则',
                'verbose_name_plural': '频度规则',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='servicepackageservicesship',
            name='duration',
            field=models.DurationField(blank=True, help_text='例如：3 days, 22:00:00', null=True, verbose_name='持续周期'),
        ),
        migrations.AddField(
            model_name='servicepackageservicesship',
            name='frequency_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.frequencyrule', verbose_name='频度'),
        ),
    ]
