# Generated by Django 4.0 on 2023-10-07 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0013_alter_service_options_l1service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='l1service',
            name='end_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_service', to='define_operand.service', verbose_name='结束作业'),
        ),
        migrations.AlterField(
            model_name='l1service',
            name='include_services',
            field=models.ManyToManyField(blank=True, related_name='include_services', to='define_operand.Service', verbose_name='包含作业'),
        ),
        migrations.AlterField(
            model_name='l1service',
            name='start_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_service', to='define_operand.service', verbose_name='起始作业'),
        ),
    ]
