# Generated by Django 4.0 on 2022-03-09 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0014_frequencyrule_servicepackageservicesship_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencyrule',
            name='description',
        ),
        migrations.AlterField(
            model_name='frequencyrule',
            name='cycle_option',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '每天'), (1, '每周'), (2, '每月'), (3, '每季'), (4, '每年')], default=0, null=True, verbose_name='周期'),
        ),
        migrations.AlterField(
            model_name='serviceoperationsship',
            name='system_operand',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'define_operand'), ('model', 'systemoperand'), ('applicable__in', [1, 3])), null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.systemoperand', verbose_name='系统作业'),
        ),
    ]
