# Generated by Django 4.0 on 2022-02-25 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0014_alter_event_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='name_new',
            new_name='name_icpc',
        ),
    ]
