# Generated by Django 4.0 on 2023-10-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0014_alter_l1service_end_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='l1service',
            name='include_services',
        ),
    ]
