# Generated by Django 4.0 on 2022-03-09 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0015_remove_frequencyrule_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoperationsship',
            name='system_operand',
            field=models.ForeignKey(blank=True, limit_choices_to=[1, 3], null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.systemoperand', verbose_name='系统作业'),
        ),
    ]
