# Generated by Django 4.0 on 2024-03-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0015_remove_l1service_include_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerule',
            name='receive_data_from',
            field=models.ManyToManyField(blank=True, related_name='receive_data_from', to='define_operand.Service', verbose_name='接收数据'),
        ),
    ]
