# Generated by Django 4.0 on 2024-04-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0016_servicerule_receive_data_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcomponentssetting',
            name='inherit_value',
            field=models.BooleanField(default=True, verbose_name='继承值'),
        ),
        migrations.AddField(
            model_name='formlistcomponentssetting',
            name='inherit_value',
            field=models.BooleanField(default=True, verbose_name='继承值'),
        ),
        migrations.AlterField(
            model_name='servicerule',
            name='passing_data',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '否'), (1, '接收')], default=0, null=True, verbose_name='接收表单'),
        ),
    ]
