# Generated by Django 4.0 on 2022-03-09 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0016_alter_serviceoperationsship_system_operand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoperationsship',
            name='system_operand',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('applicable__in', [0, 3])), null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.systemoperand', verbose_name='系统作业'),
        ),
        migrations.AlterField(
            model_name='servicepackageservicesship',
            name='system_operand',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('applicable__in', [1, 3])), null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.systemoperand', verbose_name='系统作业'),
        ),
    ]
