# Generated by Django 4.0 on 2024-04-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0017_formcomponentssetting_inherit_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buessinessform',
            name='form_fields',
            field=models.JSONField(blank=True, null=True, verbose_name='表单字段'),
        ),
    ]
