# Generated by Django 4.0 on 2022-03-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0017_alter_serviceoperationsship_system_operand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencyrule',
            name='cycle_option',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '总共'), (1, '每天'), (2, '每周'), (3, '每月'), (4, '每季'), (5, '每年')], default=0, null=True, verbose_name='周期'),
        ),
    ]
