# Generated by Django 4.0 on 2024-04-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0018_buessinessform_form_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerule',
            name='receive_data_from',
        ),
    ]
