# Generated by Django 4.0 on 2022-03-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0020_remove_serviceoperationsship_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceeventroute',
            name='interval_rule',
        ),
        migrations.RemoveField(
            model_name='serviceeventroute',
            name='service',
        ),
        migrations.RemoveField(
            model_name='serviceeventroute',
            name='service_event',
        ),
        migrations.DeleteModel(
            name='ServiceEvent',
        ),
        migrations.DeleteModel(
            name='ServiceEventRoute',
        ),
    ]
