# Generated by Django 4.0 on 2022-03-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0021_remove_serviceeventroute_interval_rule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='execute_datetime',
        ),
        migrations.RemoveField(
            model_name='service',
            name='execute_datetime',
        ),
        migrations.AddField(
            model_name='operation',
            name='execution_time_frame',
            field=models.DurationField(blank=True, null=True, verbose_name='执行时限'),
        ),
        migrations.AddField(
            model_name='service',
            name='execution_time_frame',
            field=models.DurationField(blank=True, null=True, verbose_name='执行时限'),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='execution_time_frame',
            field=models.DurationField(blank=True, null=True, verbose_name='执行时限'),
        ),
    ]
