# Generated by Django 4.0 on 2022-03-11 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0022_remove_operation_execute_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('expression', models.CharField(blank=True, default='completed', max_length=1024, null=True, verbose_name='规则')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='事件描述')),
                ('event_rule_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='业务规则ID')),
            ],
            options={
                'verbose_name': '业务规则',
                'verbose_name_plural': '业务规则',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='serviceoperationsship',
            name='buessiness_rule',
        ),
        migrations.RemoveField(
            model_name='servicepackageservicesship',
            name='buessiness_rule',
        ),
        migrations.DeleteModel(
            name='BuessinessRule',
        ),
        migrations.AddField(
            model_name='serviceoperationsship',
            name='event_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.eventrule', verbose_name='事件规则'),
        ),
        migrations.AddField(
            model_name='servicepackageservicesship',
            name='event_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.eventrule', verbose_name='事件规则'),
        ),
    ]
