# Generated by Django 4.0 on 2022-03-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0023_eventrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='awaiting_time_frame',
            field=models.DurationField(blank=True, null=True, verbose_name='等待执行时限'),
        ),
        migrations.AddField(
            model_name='service',
            name='awaiting_time_frame',
            field=models.DurationField(blank=True, null=True, verbose_name='等待执行时限'),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='awaiting_time_frame',
            field=models.DurationField(blank=True, null=True, verbose_name='等待执行时限'),
        ),
    ]
