# Generated by Django 4.0 on 2022-03-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0024_operation_awaiting_time_frame_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrule',
            name='detection_scope',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '所有个人表单'), (1, '服务包表单'), (2, '单元服务表单')], default=0, null=True, verbose_name='检测范围'),
        ),
        migrations.AlterField(
            model_name='eventrule',
            name='expression',
            field=models.TextField(blank=True, default='completed', max_length=1024, null=True, verbose_name='表达式'),
        ),
    ]
