# Generated by Django 4.0 on 2022-03-11 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0001_initial'),
        ('define_operand', '0025_eventrule_detection_scope_alter_eventrule_expression'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventrule',
            options={'ordering': ['id'], 'verbose_name': '事件规则', 'verbose_name_plural': '事件规则'},
        ),
        migrations.AlterField(
            model_name='eventrule',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='事件描述'),
        ),
        migrations.AlterField(
            model_name='eventrule',
            name='detection_scope',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '所有历史表单'), (1, '本次服务表单'), (2, '单元服务表单')], default=1, null=True, verbose_name='检测范围'),
        ),
        migrations.AlterField(
            model_name='eventrule',
            name='expression',
            field=models.CharField(blank=True, default='completed', max_length=1024, null=True, verbose_name='表达式'),
        ),
        migrations.CreateModel(
            name='EventExpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('operator', models.PositiveSmallIntegerField(blank=True, choices=[(0, '等于'), (1, '不等于'), (2, '大于'), (3, '小于'), (4, '大于等于'), (5, '小于等于'), (6, '包含'), (7, '不包含'), (8, '在...里'), (9, '不在...里')], null=True, verbose_name='操作符')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='值')),
                ('connection_operator', models.PositiveSmallIntegerField(blank=True, choices=[(0, '且'), (1, '或')], null=True, verbose_name='连接操作符')),
                ('event_expression_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='事件表达式ID')),
                ('event_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_operand.eventrule', verbose_name='事件规则')),
                ('icpc_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define.component', verbose_name='字段')),
            ],
            options={
                'verbose_name': '事件表达式',
                'verbose_name_plural': '事件表达式',
                'ordering': ['id'],
            },
        ),
    ]
