# Generated by Django 4.0 on 2022-03-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0026_alter_eventrule_options_alter_eventrule_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventexpression',
            name='label',
        ),
        migrations.RemoveField(
            model_name='eventexpression',
            name='name',
        ),
        migrations.AlterField(
            model_name='eventexpression',
            name='value',
            field=models.CharField(blank=True, help_text='多个值用英文逗号分隔', max_length=255, null=True, verbose_name='值'),
        ),
    ]
