# Generated by Django 4.0 on 2022-03-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0027_remove_eventexpression_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrule',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='权重'),
        ),
    ]
