# Generated by Django 4.0 on 2022-03-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0028_eventrule_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackageservicesship',
            name='next_service_confirmation_required',
            field=models.BooleanField(default=False, verbose_name='需要后续服务确认'),
        ),
    ]
