# Generated by Django 4.0 on 2022-03-09 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('define', '0001_initial'),
        ('define_icpc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('label', models.CharField(max_length=100, unique=True, verbose_name='视图名称')),
                ('is_inquiry', models.BooleanField(default=False, verbose_name='仅用于查询')),
                ('style', models.CharField(choices=[('detail', '详情'), ('list', '列表')], default='detail', max_length=50, verbose_name='风格')),
                ('meta_data', models.JSONField(blank=True, null=True, verbose_name='视图元数据')),
                ('baseform_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='基础视图ID')),
            ],
            options={
                'verbose_name': '基础视图',
                'verbose_name_plural': '基础视图',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BuessinessForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('label', models.CharField(max_length=100, unique=True, verbose_name='表单名称')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='表单说明')),
                ('meta_data', models.JSONField(blank=True, null=True, verbose_name='元数据')),
                ('buessiness_form_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='业务表单ID')),
                ('components', models.ManyToManyField(blank=True, to='define.Component', verbose_name='字段')),
                ('components_groups', models.ManyToManyField(blank=True, to='define.ComponentsGroup', verbose_name='组件')),
            ],
            options={
                'verbose_name': '业务表单',
                'verbose_name_plural': '业务表单',
            },
        ),
        migrations.CreateModel(
            name='FormEntityShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_base_infomation', models.BooleanField(default=False, verbose_name='基本信息表')),
                ('form_entity_ship_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='实体表单关系ID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='define.managedentity', verbose_name='隶属实体')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='define_form.buessinessform', verbose_name='业务表单')),
            ],
            options={
                'verbose_name': '表单和实体关系',
                'verbose_name_plural': '表单和实体关系',
            },
        ),
        migrations.CreateModel(
            name='CombineForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('label', models.CharField(max_length=100, unique=True, verbose_name='表单名称')),
                ('is_base', models.BooleanField(default=False, verbose_name='基础视图')),
                ('meta_data', models.JSONField(blank=True, null=True, verbose_name='视图元数据')),
                ('combineform_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='组合视图ID')),
                ('forms', models.ManyToManyField(blank=True, to='define_form.BaseForm', verbose_name='可用视图')),
                ('managed_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define.managedentity', verbose_name='实体类型')),
                ('name_icpc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_icpc.icpc', verbose_name='ICPC编码')),
            ],
            options={
                'verbose_name': '组合视图',
                'verbose_name_plural': '组合视图',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='buessinessform',
            name='managed_entity',
            field=models.ManyToManyField(blank=True, through='define_form.FormEntityShip', to='define.ManagedEntity', verbose_name='隶属实体'),
        ),
        migrations.AddField(
            model_name='buessinessform',
            name='name_icpc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_icpc.icpc', verbose_name='ICPC编码'),
        ),
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('label', models.CharField(max_length=100, unique=True, verbose_name='表单名称')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('is_base_infomation', models.BooleanField(default=False, verbose_name='基础信息表')),
                ('basemodel_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='基础表单ID')),
                ('components', models.ManyToManyField(to='define.Component', verbose_name='字段')),
                ('managed_entity', models.ManyToManyField(blank=True, to='define.ManagedEntity', verbose_name='关联实体')),
                ('name_icpc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_icpc.icpc', verbose_name='ICPC编码')),
            ],
            options={
                'verbose_name': '基础表单',
                'verbose_name_plural': '基础表单',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='baseform',
            name='basemodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='define_form.basemodel', verbose_name='基础表单'),
        ),
        migrations.AddField(
            model_name='baseform',
            name='components',
            field=models.ManyToManyField(to='define.Component', verbose_name='字段'),
        ),
    ]
