# Generated by Django 4.0 on 2022-03-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buessinessform',
            name='components',
        ),
        migrations.RemoveField(
            model_name='buessinessform',
            name='components_groups',
        ),
        migrations.RemoveField(
            model_name='buessinessform',
            name='managed_entity',
        ),
        migrations.RemoveField(
            model_name='buessinessform',
            name='name_icpc',
        ),
        migrations.RemoveField(
            model_name='formentityship',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='formentityship',
            name='form',
        ),
    ]
