# Generated by Django 4.0 on 2022-03-03 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combineform',
            name='forms',
        ),
    ]
