# Generated by Django 4.0 on 2022-02-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseform',
            name='baseform_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='基础视图ID'),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='basemodel_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='基础表单ID'),
        ),
        migrations.AddField(
            model_name='combineform',
            name='combineform_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='组合视图ID'),
        ),
    ]
