# Generated by Django 4.0 on 2022-02-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedentity',
            name='app_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='实体app名'),
        ),
        migrations.AddField(
            model_name='managedentity',
            name='display_field',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='显示字段'),
        ),
        migrations.AddField(
            model_name='managedentity',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='实体model名'),
        ),
        migrations.AddField(
            model_name='managedentity',
            name='related_field',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='关联字段'),
        ),
        migrations.AlterField(
            model_name='managedentity',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='管理实体名称'),
        ),
        migrations.AlterField(
            model_name='managedentity',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Entity name'),
        ),
    ]
