# Generated by Django 4.0 on 2022-01-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='managed_entity',
            field=models.ManyToManyField(blank=True, to='define_form.ManagedEntity', verbose_name='关联实体'),
        ),
    ]
