# Generated by Django 4.0 on 2022-02-19 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0006_managedentity'),
        ('define_form', '0002_managedentity_app_name_managedentity_display_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='managed_entity',
            field=models.ManyToManyField(blank=True, to='define.ManagedEntity', verbose_name='关联实体'),
        ),
        migrations.AlterField(
            model_name='combineform',
            name='managed_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define.managedentity', verbose_name='实体类型'),
        ),
        migrations.DeleteModel(
            name='ManagedEntity',
        ),
    ]
