# Generated by Django 4.0 on 2022-03-05 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0002_componentsgroup'),
        ('define_dict', '0002_alter_managedentity_model_name'),
        ('define_form', '0002_buessinessform_entityformship_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormEntityShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_base_infomation', models.BooleanField(default=False, verbose_name='基本信息表')),
                ('form_entity_ship_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='实体表单关系ID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='define_dict.managedentity', verbose_name='隶属实体')),
            ],
            options={
                'verbose_name': '表单和实体关系',
                'verbose_name_plural': '表单和实体关系',
            },
        ),
        migrations.AlterField(
            model_name='buessinessform',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='表单说明'),
        ),
        migrations.AlterField(
            model_name='buessinessform',
            name='managed_entity',
            field=models.ManyToManyField(blank=True, null=True, through='define_form.FormEntityShip', to='define_dict.ManagedEntity', verbose_name='隶属实体'),
        ),
        migrations.DeleteModel(
            name='EntityFormShip',
        ),
        migrations.AddField(
            model_name='formentityship',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='define_form.buessinessform', verbose_name='业务表单'),
        ),
        migrations.AddField(
            model_name='formentityship',
            name='relation_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='define.component', verbose_name='关联字段'),
        ),
    ]
