# Generated by Django 4.0 on 2022-03-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_form', '0002_alter_basemodel_name_icpc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combineform',
            name='forms_new',
            field=models.ManyToManyField(blank=True, to='define_form.BaseForm', verbose_name='基础视图'),
        ),
    ]
