# Generated by Django 4.0 on 2022-03-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_form', '0002_remove_combineform_forms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combineform',
            name='forms_new',
        ),
        migrations.AddField(
            model_name='combineform',
            name='forms',
            field=models.ManyToManyField(blank=True, to='define_form.BaseForm', verbose_name='可用视图'),
        ),
    ]
