# Generated by Django 4.0 on 2022-03-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0002_buessinessform_alter_systemoperand_options_and_more'),
        ('define_form', '0002_remove_buessinessform_components_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuessinessForm',
        ),
        migrations.DeleteModel(
            name='FormEntityShip',
        ),
    ]
