# Generated by Django 4.0 on 2022-03-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_dict', '0002_alter_managedentity_model_name'),
        ('define_form', '0003_formentityship_alter_buessinessform_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buessinessform',
            name='managed_entity',
            field=models.ManyToManyField(blank=True, through='define_form.FormEntityShip', to='define_dict.ManagedEntity', verbose_name='隶属实体'),
        ),
    ]
