# Generated by Django 4.0 on 2022-02-20 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_dict', '0002_managedentity'),
        ('define_form', '0003_alter_basemodel_managed_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='managed_entity',
            field=models.ManyToManyField(blank=True, to='define_dict.ManagedEntity', verbose_name='关联实体'),
        ),
        migrations.AlterField(
            model_name='combineform',
            name='managed_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_dict.managedentity', verbose_name='实体类型'),
        ),
    ]
