# Generated by Django 4.0 on 2022-02-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_icpc', '0006_icpc'),
        ('define_form', '0004_alter_basemodel_managed_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='name_new',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_icpc.icpc', verbose_name='表单名称'),
        ),
    ]
