# Generated by Django 4.0 on 2022-02-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0013_rename_name_new_boolfield_name_icpc_and_more'),
        ('define_form', '0006_combineform_name_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basemodel',
            old_name='name_new',
            new_name='name_icpc',
        ),
        migrations.RenameField(
            model_name='combineform',
            old_name='name_new',
            new_name='name_icpc',
        ),
        migrations.AlterField(
            model_name='baseform',
            name='components',
            field=models.ManyToManyField(to='define.Component', verbose_name='字段'),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='components',
            field=models.ManyToManyField(to='define.Component', verbose_name='字段'),
        ),
    ]
