design_data = {
    'index': [
        {'boolfields': 'BoolField'}, 
        {'characterfields': 'CharacterField'}, 
        {'numberfields': 'NumberField'}, 
        {'dtfields': 'DTField'}, 
        {'relatedfields': 'RelatedField'}, 
        {'choicefields': 'ChoiceField'}, 
        {'components': 'Component'}, 
        {'diclists': 'DicList'}, 
        {'managedentities': 'ManagedEntity'}, 
        {'basemodels': 'BaseModel'}, 
        {'baseforms': 'BaseForm'}, 
        {'combineforms': 'CombineForm'}, 
        {'operandviews': 'OperandVie}'},
    ],

    'managedentities': [
        {'id': 5, 'name': 'customer', 'label': '客户', 'description': None}, 
        {'id': 6, 'name': 'staff', 'label': '员工', 'description': None}, 
        {'id': 7, 'name': 'medicine', 'label': '药品', 'description': None}, 
        {'id': 8, 'name': 'device', 'label': '设备', 'description': None}
    ],

    'diclists': [
        {'id': 34, 'name': 'drug_list', 'label': '药品清单', 'related_field': 'value', 'content': ''}, 
        {'id': 35, 'name': 'icpc3_symptoms_and_problems', 'label': '症状和问题', 'related_field': 'iname', 'content': ''}, 
        {'id': 36, 'name': 'character', 'label': '性格', 'related_field': 'value', 'content': '外向\n内向'}, 
        {'id': 37, 'name': 'satisfaction', 'label': '满意度', 'related_field': 'value', 'content': '很满意\n满意\n既非满意也非不满意\n不满意\n很不满意'}, 
        {'id': 38, 'name': 'frequency', 'label': '频次', 'related_field': 'value', 'content': '经常\n偶尔\n从无'}, 
        {'id': 39, 'name': 'state_degree', 'label': '状态程度', 'related_field': 'value', 'content': '非常好\n还不错\n不太好\n非常糟'}, 
        {'id': 40, 'name': 'comparative_expression', 'label': '比较表达', 'related_field': 'value', 'content': '改善很大\n有一定改善\n没变化\n变更差了'}, 
        {'id': 41, 'name': 'sports_preference', 'label': '运动类型', 'related_field': 'value', 'content': '有氧运动\n无氧运动\n有氧无氧交替运动\n不运动'}, 
        {'id': 42, 'name': 'exercise_time', 'label': '运动时长', 'related_field': 'value', 'content': '半小时以内\n半小时到一个半小时\n一个半小时以上'}, 
        {'id': 43, 'name': 'convenience', 'label': '便捷程度', 'related_field': 'value', 'content': '非常不方便\n不方便\n比较方便\n非常方便'}, 
        {'id': 44, 'name': 'icpc5_evaluation_and_diagnoses', 'label': '评估和诊断', 'related_field': 'iname', 'content': ''}, 
        {'id': 45, 'name': 'family_relationship', 'label': '家庭成员关系', 'related_field': 'value', 'content': '户主\n配偶\n父母\n子女\n祖父母\n孙子女\n兄弟姐妹\n其他成员'}, 
        {'id': 46, 'name': 'normality', 'label': '正常性判断', 'related_field': 'value', 'content': '正常\n异常'}, 
        {'id': 47, 'name': 'service_role', 'label': '服务角色', 'related_field': 'value', 'content': '健康管理师\n护士\n医生助理\n医生\n化验\n质量管理\n药士\n药剂师\n公卫\n管理者\n影像医师\n康复理疗师\n中医师'}, 
        {'id': 48, 'name': 'institutions_list', 'label': '机构清单', 'related_field': 'value', 'content': ''}, 
        {'id': 49, 'name': 'dorsal_artery_pulsation', 'label': '足背动脉搏动情况', 'related_field': 'value', 'content': '触及正常\n触及正常\n减弱\n消失'}, 
        {'id': 50, 'name': 'hearing', 'label': '听力', 'related_field': 'value', 'content': '听见\n听不清或无法听见'}, 
        {'id': 51, 'name': 'icpc7_treatments', 'label': '治疗', 'related_field': 'iname', 'content': ''}, 
        {'id': 52, 'name': 'lips', 'label': '口唇', 'related_field': 'value', 'content': '红润\n苍白\n发绀\n皲裂\n疱疹'}, 
        {'id': 53, 'name': 'dentition', 'label': '齿列', 'related_field': 'value', 'content': '正常\n缺齿\n龋齿\n义齿（假牙）'}, 
        {'id': 54, 'name': 'pharynx', 'label': '咽部', 'related_field': 'value', 'content': '无充血\n充血\n淋巴滤泡增生'}, 
        {'id': 55, 'name': 'life_event', 'label': '生活事件', 'related_field': 'value', 'content': '丧偶\n父母死亡\n子女死亡\n离婚\n失业\n家属病重\n恋爱\n结婚\n生子'}, 
        {'id': 56, 'name': 'edema', 'label': '水肿情况', 'related_field': 'value', 'content': '无水肿\n单侧水肿\n双侧不对称水肿\n双侧对称水肿'}, 
        {'id': 57, 'name': 'icpc1_register_logins', 'label': '注册登录（行政管理）', 'related_field': 'iname', 'content': ''}, 
        {'id': 58, 'name': 'gender', 'label': '性别', 'related_field': 'value', 'content': '男\n女'}, 
        {'id': 59, 'name': 'nationality', 'label': '民族', 'related_field': 'value', 'content': '汉族\n少数民族'}, 
        {'id': 60, 'name': 'marital_status', 'label': '婚姻状况', 'related_field': 'value', 'content': '未婚\n已婚\n离异\n丧偶'}, 
        {'id': 61, 'name': 'education', 'label': '文化程度', 'related_field': 'value', 'content': '博士\n硕士\n本科\n大专\n中专技校\n高中\n初中\n小学\n文盲或半文盲'}, 
        {'id': 62, 'name': 'occupational_status', 'label': '职业状况', 'related_field': 'value', 'content': '在职\n失业\n退休'}, 
        {'id': 63, 'name': 'medical_expenses_burden', 'label': '医疗费用负担', 'related_field': 'value', 'content': '职工医疗保险\n城镇居民医疗保险\n商业保险\n自费\n公费\n贫困救助'}, 
        {'id': 64, 'name': 'type_of_residence', 'label': '居住类型', 'related_field': 'value', 'content': '常住\n非常住'}, 
        {'id': 65, 'name': 'blood_type', 'label': '血型', 'related_field': 'value', 'content': 'A型\nB型\nO型\nAB型\nA+型\nA-型\nB+型\nB-型\nO+型\nO-型\nAB+型\nAB-型\n不详'}, 
        {'id': 66, 'name': 'employee_list', 'label': '职员表', 'related_field': 'value', 'content': ''}
    ],

    'boolfields': [
        {'id': 17, 'name': 'boolfield_is_life_fun', 'label': '您觉得生活是否有乐趣吗', 'type': '0', 'required': False, 'default': '0'}, 
        {'id': 18, 'name': 'boolfield_do_you_feel_pressured_at_work', 'label': '是否感觉到工作压力大', 'type': '0', 'required': False, 'default': '0'}, 
        {'id': 19, 'name': 'boolfield_do_you_often_work_overtime', 'label': '是否经常加班', 'type': '0', 'required': False, 'default': '0'}, 
        {'id': 20, 'name': 'boolfield_is_the_diet_regular', 'label': '饮食是否规律', 'type': '0', 'required': False, 'default': '0'}, 
        {'id': 21, 'name': 'boolfield_is_the_diet_proportion_healthy', 'label': '饮食比例是否健康', 'type': '0', 'required': False, 'default': '0'}, 
        {'id': 22, 'name': 'boolfield_whether_the_bowel_movements_are_regular', 'label': '大便是否规律', 'type': '0', 'required': False, 'default': '0'}, 
        {'id': 23, 'name': 'boolfield_whether_to_drink_alcohol', 'label': '是否饮酒', 'type': '0', 'required': False, 'default': '0'}, 
        {'id': 24, 'name': 'boolfield_do_you_smoke', 'label': '是否吸烟', 'type': '0', 'required': False, 'default': '0'}, 
        {'id': 25, 'name': 'boolfield_insomnia', 'label': '是否有失眠情况', 'type': '0', 'required': False, 'default': '0'}, 
        {'id': 26, 'name': 'boolfield_is_it_easy_to_get_sick', 'label': '是否比别人容易生病', 'type': '0', 'required': False, 'default': '0'}, 
        {'id': 27, 'name': 'boolfield_whether_the_living_environment_is_clean_and_hygienic', 'label': '居住环境是否干净卫生', 'type': '0', 'required': False, 'default': '0'}, 
        {'id': 28, 'name': 'boolfield_is_drinking_water_healthy', 'label': '饮水是否健康', 'type': '0', 'required': False, 'default': '0'}, 
        {'id': 29, 'name': 'boolfield_whether_there_is_noise_pollution', 'label': '是否有噪声污染', 'type': '0', 'required': False, 'default': '0'}, 
        {'id': 30, 'name': 'boolfield_whether_there_is_air_pollution', 'label': '是否有空气污染', 'type': '0', 'required': False, 'default': '0'}, 
        {'id': 31, 'name': 'boolfield_whether_there_is_other_pollution', 'label': '是否有其他污染', 'type': '0', 'required': False, 'default': '0'}, 
        {'id': 32, 'name': 'boolfield_contract_signatory', 'label': '合同签约户', 'type': '1', 'required': False, 'default': '0'}
    ],

    'characterfields': [
        {'id': 25, 'name': 'characterfield_supplementary_description_of_the_condition', 'label': '病情补充描述', 'type': 'CharField', 'length': 255, 'required': False, 'default': None}, 
        {'id': 26, 'name': 'characterfield_working_hours_per_day', 'label': '每天工作及工作往返总时长', 'type': 'TextField', 'length': 255, 'required': False, 'default': None}, 
        {'id': 27, 'name': 'characterfield_average_sleep_duration', 'label': '平均睡眠时长', 'type': 'CharField', 'length': 255, 'required': False, 'default': None}, 
        {'id': 28, 'name': 'characterfield_duration_of_insomnia', 'label': '持续失眠时间', 'type': 'CharField', 'length': 255, 'required': False, 'default': None}, 
        {'id': 29, 'name': 'characterfield_name', 'label': '姓名', 'type': 'CharField', 'length': 255, 'required': False, 'default': None}, 
        {'id': 30, 'name': 'characterfield_gender', 'label': '性别', 'type': 'CharField', 'length': 255, 'required': False, 'default': None}, 
        {'id': 31, 'name': 'characterfield_age', 'label': '年龄', 'type': 'CharField', 'length': 255, 'required': False, 'default': None}, 
        {'id': 32, 'name': 'characterfield_identification_number', 'label': '身份证号码', 'type': 'CharField', 'length': 255, 'required': False, 'default': None}, 
        {'id': 33, 'name': 'characterfield_contact_information', 'label': '联系电话', 'type': 'CharField', 'length': 255, 'required': False, 'default': None}, 
        {'id': 34, 'name': 'characterfield_contact_address', 'label': '联系地址', 'type': 'CharField', 'length': 255, 'required': False, 'default': None}, 
        {'id': 35, 'name': 'characterfield_practice_qualification', 'label': '执业资质', 'type': 'CharField', 'length': 255, 'required': False, 'default': None}, 
        {'id': 36, 'name': 'characterfield_password_setting', 'label': '密码设置', 'type': 'CharField', 'length': 255, 'required': False, 'default': None}, 
        {'id': 37, 'name': 'characterfield_confirm_password', 'label': '确认密码', 'type': 'CharField', 'length': 255, 'required': False, 'default': None}, 
        {'id': 38, 'name': 'characterfield_expertise', 'label': '专长', 'type': 'CharField', 'length': 255, 'required': False, 'default': None}, 
        {'id': 39, 'name': 'characterfield_practice_time', 'label': '执业时间', 'type': 'CharField', 'length': 255, 'required': False, 'default': None}, 
        {'id': 40, 'name': 'characterfield_username', 'label': '用户名', 'type': 'CharField', 'length': 255, 'required': False, 'default': None}, 
        {'id': 41, 'name': 'characterfield_password', 'label': '密码', 'type': 'CharField', 'length': 255, 'required': False, 'default': None}, 
        {'id': 42, 'name': 'characterfield_service_role', 'label': '服务角色', 'type': 'CharField', 'length': 255, 'required': False, 'default': None}, 
        {'id': 43, 'name': 'characterfield_left_eye_vision', 'label': '左眼视力', 'type': 'CharField', 'length': 255, 'required': False, 'default': None}, 
        {'id': 44, 'name': 'characterfield_right_eye_vision', 'label': '右眼视力', 'type': 'CharField', 'length': 255, 'required': False, 'default': None}, 
        {'id': 45, 'name': 'characterfield_resident_file_number', 'label': '居民档案号', 'type': 'CharField', 'length': 255, 'required': False, 'default': None}, 
        {'id': 46, 'name': 'characterfield_family_address', 'label': '家庭地址', 'type': 'CharField', 'length': 255, 'required': False, 'default': None}, 
        {'id': 47, 'name': 'characterfield_contact_number', 'label': '联系电话', 'type': 'CharField', 'length': 255, 'required': False, 'default': None}, 
        {'id': 48, 'name': 'characterfield_medical_ic_card_number', 'label': '医疗ic卡号', 'type': 'CharField', 'length': 255, 'required': False, 'default': None}
    ],

    'numberfields': [
        {'id': 12, 'name': 'numberfield_body_temperature', 'label': '体温', 'type': 'IntegerField', 'max_digits': 10, 'decimal_places': 2, 'standard_value': None, 'up_limit': 37.4, 'down_limit': 36.0, 'unit': '℃', 'default': None, 'required': False}, 
        {'id': 13, 'name': 'numberfield_pulse', 'label': '脉搏', 'type': 'IntegerField', 'max_digits': 10, 'decimal_places': 2, 'standard_value': None, 'up_limit': 100.0, 'down_limit': 60.0, 'unit': '次/分钟', 'default': None, 'required': False}, 
        {'id': 14, 'name': 'numberfield_respiratory_rate', 'label': '呼吸频率', 'type': 'IntegerField', 'max_digits': 10, 'decimal_places': 2, 'standard_value': None, 'up_limit': 20.0, 'down_limit': 10.0, 'unit': '次/分钟', 'default': None, 'required': False}, 
        {'id': 15, 'name': 'numberfield_hight', 'label': '身高', 'type': 'IntegerField', 'max_digits': 10, 'decimal_places': 2, 'standard_value': None, 'up_limit': None, 'down_limit': None, 'unit': 'cm', 'default': None, 'required': False}, 
        {'id': 16, 'name': 'numberfield_weight', 'label': '体重', 'type': 'IntegerField', 'max_digits': 10, 'decimal_places': 2, 'standard_value': None, 'up_limit': None, 'down_limit': None, 'unit': 'kg', 'default': None, 'required': False}, 
        {'id': 17, 'name': 'numberfield_body_mass_index', 'label': '体质指数', 'type': 'IntegerField', 'max_digits': 10, 'decimal_places': 2, 'standard_value': None, 'up_limit': 23.9, 'down_limit': 18.5, 'unit': None, 'default': None, 'required': False}, 
        {'id': 18, 'name': 'numberfield_blood_transfusion', 'label': '输血量', 'type': 'IntegerField', 'max_digits': 10, 'decimal_places': 2, 'standard_value': None, 'up_limit': 400.0, 'down_limit': None, 'unit': 'ml', 'default': None, 'required': False}, 
        {'id': 19, 'name': 'numberfield_systolic_blood_pressure', 'label': '收缩压', 'type': 'IntegerField', 'max_digits': 10, 'decimal_places': 2, 'standard_value': None, 'up_limit': 139.0, 'down_limit': 90.0, 'unit': 'mmol/L', 'default': None, 'required': False}, 
        {'id': 20, 'name': 'numberfield_diastolic_blood_pressure', 'label': '舒张压', 'type': 'IntegerField', 'max_digits': 10, 'decimal_places': 2, 'standard_value': None, 'up_limit': 89.0, 'down_limit': 60.0, 'unit': 'mmol/L', 'default': None, 'required': False}, 
        {'id': 21, 'name': 'numberfield_kong_fu_xue_tang', 'label': '空腹血糖', 'type': 'DecimalField', 'max_digits': 10, 'decimal_places': 2, 'standard_value': None, 'up_limit': 7.0, 'down_limit': 3.9, 'unit': 'mmol/L', 'default': None, 'required': False}, 
        {'id': 22, 'name': 'numberfield_tang_hua_xue_hong_dan_bai', 'label': '糖化血红蛋白', 'type': 'DecimalField', 'max_digits': 10, 'decimal_places': 2, 'standard_value': None, 'up_limit': 6.0, 'down_limit': 4.0, 'unit': '%', 'default': None, 'required': False}
    ],

    'dtfields': [
        {'id': 4, 'name': 'datetimefield_date', 'label': '日期', 'type': 'DateTimeField', 'default_now': False, 'required': False}, 
        {'id': 5, 'name': 'datetimefield_time_of_diagnosis', 'label': '确诊时间', 'type': 'DateTimeField', 'default_now': False, 'required': False}, 
        {'id': 6, 'name': 'datetimefield_date_of_birth', 'label': '出生日期', 'type': 'DateTimeField', 'default_now': False, 'required': False}
    ],

    'relatedfields': [
        {'id': 44, 'name': 'relatedfield_drug_name', 'label': '药品名称', 'type': 'SelectMultiple', 'related_content': 'drug_list', 'related_field': 'value'},
        {'id': 45, 'name': 'relatedfield_symptom_list', 'label': '症状', 'type': 'SelectMultiple', 'related_content': 'icpc3_symptoms_and_problems', 'related_field': 'iname'}, 
        {'id': 46, 'name': 'relatedfield_personality_tendency', 'label': '性格倾向', 'type': 'RadioSelect', 'related_content': 'character', 'related_field': 'value'}, 
        {'id': 47, 'name': 'relatedfield_are_you_satisfied_with_the_job_and_life', 'label': '对目前生活和工作满意吗', 'type': 'Select', 'related_content': 'satisfaction', 'related_field': 'value'}, 
        {'id': 48, 'name': 'relatedfield_are_you_satisfied_with_your_adaptability', 'label': '对自己的适应能力满意吗', 'type': 'Select', 'related_content': 'satisfaction', 'related_field': 'value'}, 
        {'id': 49, 'name': 'relatedfield_can_you_get_encouragement_and_support_from_family', 'label': '是否能得到家人朋友的鼓励和支持', 'type': 'Select', 'related_content': 'frequency', 'related_field': 'value'}, 
        {'id': 50, 'name': 'relatedfield_drinking_frequency', 'label': '饮酒频次', 'type': 'RadioSelect', 'related_content': 'frequency', 'related_field': 'value'}, 
        {'id': 51, 'name': 'relatedfield_smoking_frequency', 'label': '吸烟频次', 'type': 'RadioSelect', 'related_content': 'frequency', 'related_field': 'value'}, 
        {'id': 52, 'name': 'relatedfield_own_health', 'label': '觉得自身健康状况如何', 'type': 'RadioSelect', 'related_content': 'state_degree', 'related_field': 'value'}, 
        {'id': 53, 'name': 'relatedfield_compared_to_last_year', 'label': '较之过去一年状态如何', 'type': 'Select', 'related_content': 'comparative_expression', 'related_field': 'value'}, 
        {'id': 54, 'name': 'relatedfield_sports_preference', 'label': '运动偏好', 'type': 'Select', 'related_content': 'sports_preference', 'related_field': 'value'}, 
        {'id': 55, 'name': 'relatedfield_exercise_time', 'label': '运动时长', 'type': 'RadioSelect', 'related_content': 'exercise_time', 'related_field': 'value'}, 
        {'id': 56, 'name': 'relatedfield_have_any_recent_symptoms_of_physical_discomfort', 'label': '近来有无身体不适症状', 'type': 'CheckboxSelectMultiple', 'related_content': 'icpc3_symptoms_and_problems', 'related_field': 'iname'}, 
        {'id': 57, 'name': 'relatedfield_is_the_living_environment_satisfactory', 'label': '您对居住环境满意吗', 'type': 'Select', 'related_content': 'satisfaction', 'related_field': 'value'}, 
        {'id': 58, 'name': 'relatedfield_is_the_transportation_convenient', 'label': '您所在的社区交通方便吗', 'type': 'Select', 'related_content': 'convenience', 'related_field': 'value'}, 
        {'id': 59, 'name': 'relatedfield_diseases', 'label': '病名', 'type': 'Select', 'related_content': 'icpc5_evaluation_and_diagnoses', 'related_field': 'iname'}, 
        {'id': 60, 'name': 'relatedfield_family_relationship', 'label': '家庭成员关系', 'type': 'Select', 'related_content': 'family_relationship', 'related_field': 'value'}, 
        {'id': 61, 'name': 'relatedfield_disease_name', 'label': '疾病名称', 'type': 'Select', 'related_content': 'icpc5_evaluation_and_diagnoses', 'related_field': 'iname'}, 
        {'id': 62, 'name': 'relatedfield_fundus', 'label': '眼底', 'type': 'Select', 'related_content': 'normality', 'related_field': 'value'}, 
        {'id': 63, 'name': 'relatedfield_service_role', 'label': '服务角色', 'type': 'CheckboxSelectMultiple', 'related_content': 'service_role', 'related_field': 'value'}, 
        {'id': 64, 'name': 'relatedfield_affiliation', 'label': '所属机构', 'type': 'RadioSelect', 'related_content': 'institutions_list', 'related_field': 'value'}, 
        {'id': 65, 'name': 'relatedfield_left_foot', 'label': '左脚', 'type': 'RadioSelect', 'related_content': 'dorsal_artery_pulsation', 'related_field': 'value'}, 
        {'id': 66, 'name': 'relatedfield_right_foot', 'label': '右脚', 'type': 'RadioSelect', 'related_content': 'dorsal_artery_pulsation', 'related_field': 'value'}, 
        {'id': 67, 'name': 'relatedfield_left_ear_hearing', 'label': '左耳听力', 'type': 'Select', 'related_content': 'hearing', 'related_field': 'value'}, 
        {'id': 68, 'name': 'relatedfield_right_ear_hearing', 'label': '右耳听力', 'type': 'Select', 'related_content': 'hearing', 'related_field': 'value'}, 
        {'id': 69, 'name': 'relatedfield_name_of_operation', 'label': '手术名称', 'type': 'RadioSelect', 'related_content': 'icpc7_treatments', 'related_field': 'iname'}, 
        {'id': 70, 'name': 'relatedfield_lips', 'label': '口唇', 'type': 'RadioSelect', 'related_content': 'lips', 'related_field': 'value'}, 
        {'id': 71, 'name': 'relatedfield_dentition', 'label': '齿列', 'type': 'RadioSelect', 'related_content': 'dentition', 'related_field': 'value'}, 
        {'id': 72, 'name': 'relatedfield_pharynx', 'label': '咽部', 'type': 'Select', 'related_content': 'pharynx', 'related_field': 'value'}, 
        {'id': 73, 'name': 'relatedfield_major_life', 'label': '生活事件', 'type': 'CheckboxSelectMultiple', 'related_content': 'life_event', 'related_field': 'value'}, 
        {'id': 74, 'name': 'relatedfield_lower_extremity_edema', 'label': '下肢水肿', 'type': 'RadioSelect', 'related_content': 'edema', 'related_field': 'value'}, 
        {'id': 75, 'name': 'relatedfield_family_id', 'label': '家庭编号', 'type': 'Select', 'related_content': 'icpc1_register_logins', 'related_field': 'iname'}, 
        {'id': 76, 'name': 'relatedfield_gender', 'label': '性别', 'type': 'Select', 'related_content': 'gender', 'related_field': 'value'}, 
        {'id': 77, 'name': 'relatedfield_nationality', 'label': '民族', 'type': 'Select', 'related_content': 'nationality', 'related_field': 'value'}, 
        {'id': 78, 'name': 'relatedfield_marital_status', 'label': '婚姻状况', 'type': 'Select', 'related_content': 'marital_status', 'related_field': 'value'}, 
        {'id': 79, 'name': 'relatedfield_education', 'label': '文化程度', 'type': 'Select', 'related_content': 'education', 'related_field': 'value'}, 
        {'id': 80, 'name': 'relatedfield_occupational_status', 'label': '职业状况', 'type': 'Select', 'related_content': 'occupational_status', 'related_field': 'value'}, 
        {'id': 81, 'name': 'relatedfield_medical_expenses_burden', 'label': '医疗费用负担', 'type': 'CheckboxSelectMultiple', 'related_content': 'medical_expenses_burden', 'related_field': 'value'}, 
        {'id': 82, 'name': 'relatedfield_type_of_residence', 'label': '居住类型', 'type': 'Select', 'related_content': 'type_of_residence', 'related_field': 'value'}, 
        {'id': 83, 'name': 'relatedfield_blood_type', 'label': '血型', 'type': 'Select', 'related_content': 'blood_type', 'related_field': 'value'}, 
        {'id': 84, 'name': 'relatedfield_signed_family_doctor', 'label': '签约家庭医生', 'type': 'Select', 'related_content': 'employee_list', 'related_field': 'value'}, 
        {'id': 85, 'name': 'relatedfield_athletic_ability', 'label': '运动能力', 'type': 'Select', 'related_content': 'exercise_time', 'related_field': 'value'}, 
    ],    
    
    'basemodels': [
        {'id': 36, 'name': 'allergies_history', 'label': '过敏史', 'description': None, 'is_base_infomation': False, 'components': [{'id': 98, 'name': 'relatedfield_drug_name', 'label': '药品名称', 'content_type': 17, 'object_id': 44}], 'managed_entity': []}, 
        {'id': 37, 'name': 'out_of_hospital_self_report_survey', 'label': '院外症状自述调查', 'description': None, 'is_base_infomation': False, 'components': [{'id': 99, 'name': 'relatedfield_symptom_list', 'label': '症状', 'content_type': 17, 'object_id': 45}, {'id': 100, 'name': 'characterfield_supplementary_description_of_the_condition', 'label': '病情补充描述', 'content_type': 8, 'object_id': 25}], 'managed_entity': []}, 
        {'id': 38, 'name': 'personal_comprehensive_psychological_quality_survey', 'label': '个人心理综合素质调查', 'description': None, 'is_base_infomation': False, 'components': [{'id': 101, 'name': 'relatedfield_personality_tendency', 'label': '性格倾向', 'content_type': 17, 'object_id': 46}, {'id': 102, 'name': 'boolfield_is_life_fun', 'label': '您觉得生活是否有乐趣吗', 'content_type': 7, 'object_id': 17}], 'managed_entity': []}, 
        {'id': 39, 'name': 'personal_adaptability_assessment', 'label': '个人适应能力评估', 'description': '', 'is_base_infomation': False, 'components': [{'id': 103, 'name': 'boolfield_do_you_feel_pressured_at_work', 'label': '是否感觉到工作压力大', 'content_type': 7, 'object_id': 18}, {'id': 104, 'name': 'boolfield_do_you_often_work_overtime', 'label': '是否经常加班', 'content_type': 7, 'object_id': 19}, {'id': 105, 'name': 'characterfield_working_hours_per_day', 'label': '每天工作及工作往返总时长', 'content_type': 8, 'object_id': 26}, {'id': 106, 'name': 'relatedfield_are_you_satisfied_with_the_job_and_life', 'label': '对目前生活和工作满意吗', 'content_type': 17, 'object_id': 47}, {'id': 107, 'name': 'relatedfield_are_you_satisfied_with_your_adaptability', 'label': '对自己的适应能力满意吗', 'content_type': 17, 'object_id': 48}], 'managed_entity': []}, 
        {'id': 40, 'name': 'personal_health_behavior_survey', 'label': '个人健康行为调查', 'description': None, 'is_base_infomation': False, 'components': [{'id': 109, 'name': 'boolfield_is_the_diet_regular', 'label': '饮食是否规律', 'content_type': 7, 'object_id': 20}, {'id': 110, 'name': 'boolfield_is_the_diet_proportion_healthy', 'label': '饮食比例是否健康', 'content_type': 7, 'object_id': 21}, {'id': 111, 'name': 'boolfield_whether_the_bowel_movements_are_regular', 'label': '大便是否规律', 'content_type': 7, 'object_id': 22}, {'id': 112, 'name': 'boolfield_whether_to_drink_alcohol', 'label': '是否饮酒', 'content_type': 7, 'object_id': 23}, {'id': 113, 'name': 'relatedfield_drinking_frequency', 'label': '饮酒频次', 'content_type': 17, 'object_id': 50}, {'id': 114, 'name': 'boolfield_do_you_smoke', 'label': '是否吸烟', 'content_type': 7, 'object_id': 24}, {'id': 115, 'name': 'relatedfield_smoking_frequency', 'label': '吸烟频次', 'content_type': 17, 'object_id': 51}, {'id': 116, 'name': 'characterfield_average_sleep_duration', 'label': '平均睡眠时长', 'content_type': 8, 'object_id': 27}, {'id': 117, 'name': 'boolfield_insomnia', 'label': '是否有失眠情况', 'content_type': 7, 'object_id': 25}, {'id': 118, 'name': 'characterfield_duration_of_insomnia', 'label': '持续失眠时间', 'content_type': 8, 'object_id': 28}], 'managed_entity': []}, 
        {'id': 41, 'name': 'personal_health_assessment', 'label': '个人身体健康评估', 'description': None, 'is_base_infomation': False, 'components': [{'id': 119, 'name': 'relatedfield_own_health', 'label': '觉得自身健康状况如何', 'content_type': 17, 'object_id': 52}, {'id': 120, 'name': 'relatedfield_compared_to_last_year', 'label': '较之过去一年状态如何', 'content_type': 17, 'object_id': 53}, {'id': 121, 'name': 'relatedfield_sports_preference', 'label': '运动偏好', 'content_type': 17, 'object_id': 54}, {'id': 122, 'name': 'relatedfield_exercise_time', 'label': '运动时长', 'content_type': 17, 'object_id': 55}, {'id': 123, 'name': 'boolfield_is_it_easy_to_get_sick', 'label': '是否比别人容易生病', 'content_type': 7, 'object_id': 26}, {'id': 124, 'name': 'relatedfield_have_any_recent_symptoms_of_physical_discomfort', 'label': '近来有无身体不适症状', 'content_type': 17, 'object_id': 56}], 'managed_entity': []}, 
        {'id': 42, 'name': 'social_environment_assessment', 'label': '社会环境评估', 'description': None, 'is_base_infomation': False, 'components': [{'id': 125, 'name': 'relatedfield_is_the_living_environment_satisfactory', 'label': '您对居住环境满意吗', 'content_type': 17, 'object_id': 57}, {'id': 126, 'name': 'relatedfield_is_the_transportation_convenient', 'label': '您所在的社区交通方便吗', 'content_type': 17, 'object_id': 58}, {'id': 127, 'name': 'boolfield_whether_the_living_environment_is_clean_and_hygienic', 'label': '居住环境是否干净卫生', 'content_type': 7, 'object_id': 27}, {'id': 128, 'name': 'boolfield_is_drinking_water_healthy', 'label': '饮水是否健康', 'content_type': 7, 'object_id': 28}, {'id': 129, 'name': 'boolfield_whether_there_is_noise_pollution', 'label': '是否有噪声污染', 'content_type': 7, 'object_id': 29}, {'id': 130, 'name': 'boolfield_whether_there_is_air_pollution', 'label': '是否有空气污染', 'content_type': 7, 'object_id': 30}, {'id': 131, 'name': 'boolfield_whether_there_is_other_pollution', 'label': '是否有其他污染', 'content_type': 7, 'object_id': 31}], 'managed_entity': []}, 
        {'id': 43, 'name': 'vital_signs_check', 'label': '生命体征检查', 'description': None, 'is_base_infomation': False, 'components': [{'id': 132, 'name': 'numberfield_body_temperature', 'label': '体温', 'content_type': 15, 'object_id': 12}, {'id': 133, 'name': 'numberfield_pulse', 'label': '脉搏', 'content_type': 15, 'object_id': 13}, {'id': 134, 'name': 'numberfield_respiratory_rate', 'label': '呼吸频率', 'content_type': 15, 'object_id': 14}], 'managed_entity': []}, 
        {'id': 44, 'name': 'family_history_of_illness', 'label': '家族病史', 'description': None, 'is_base_infomation': False, 'components': [{'id': 135, 'name': 'relatedfield_diseases', 'label': '病名', 'content_type': 17, 'object_id': 59}, {'id': 136, 'name': 'relatedfield_family_relationship', 'label': '家庭成员关系', 'content_type': 17, 'object_id': 60}], 'managed_entity': []}, 
        {'id': 45, 'name': 'physical_examination', 'label': '体格检查', 'description': None, 'is_base_infomation': False, 'components': [{'id': 137, 'name': 'numberfield_hight', 'label': '身高', 'content_type': 15, 'object_id': 15}, {'id': 138, 'name': 'numberfield_weight', 'label': '体重', 'content_type': 15, 'object_id': 16}, {'id': 139, 'name': 'numberfield_body_mass_index', 'label': '体质指数', 'content_type': 15, 'object_id': 17}], 'managed_entity': []}, 
        {'id': 46, 'name': 'history_of_blood_transfusion', 'label': '输血史', 'description': None, 'is_base_infomation': False, 'components': [{'id': 140, 'name': 'datetimefield_date', 'label': '日期', 'content_type': 13, 'object_id': 4}, {'id': 141, 'name': 'numberfield_blood_transfusion', 'label': '输血量', 'content_type': 15, 'object_id': 18}], 'managed_entity': []}, 
        {'id': 47, 'name': 'history_of_trauma', 'label': '外伤史', 'description': None, 'is_base_infomation': False, 'components': [{'id': 140, 'name': 'datetimefield_date', 'label': '日期', 'content_type': 13, 'object_id': 4}, {'id': 142, 'name': 'relatedfield_disease_name', 'label': '疾病名称', 'content_type': 17, 'object_id': 61}], 'managed_entity': []}, 
        {'id': 48, 'name': 'fundus_examination', 'label': '眼底检查', 'description': None, 'is_base_infomation': False, 'components': [{'id': 143, 'name': 'relatedfield_fundus', 'label': '眼底', 'content_type': 17, 'object_id': 62}], 'managed_entity': []}, 
        {'id': 49, 'name': 'medical_history', 'label': '疾病史', 'description': None, 'is_base_infomation': False, 'components': [{'id': 142, 'name': 'relatedfield_disease_name', 'label': '疾病名称', 'content_type': 17, 'object_id': 61}, {'id': 144, 'name': 'datetimefield_time_of_diagnosis', 'label': '确诊时间', 'content_type': 13, 'object_id': 5}], 'managed_entity': []}, 
        {'id': 50, 'name': 'doctor_registry', 'label': '医生注册', 'description': None, 'is_base_infomation': False, 'components': [{'id': 145, 'name': 'characterfield_name', 'label': '姓名', 'content_type': 8, 'object_id': 29}, {'id': 146, 'name': 'characterfield_gender', 'label': '性别', 'content_type': 8, 'object_id': 30}, {'id': 147, 'name': 'characterfield_age', 'label': '年龄', 'content_type': 8, 'object_id': 31}, {'id': 148, 'name': 'characterfield_identification_number', 'label': '身份证号码', 'content_type': 8, 'object_id': 32}, {'id': 149, 'name': 'characterfield_contact_information', 'label': '联系电话', 'content_type': 8, 'object_id': 33}, {'id': 150, 'name': 'characterfield_contact_address', 'label': '联系地址', 'content_type': 8, 'object_id': 34}, {'id': 151, 'name': 'relatedfield_service_role', 'label': '服务角色', 'content_type': 17, 'object_id': 63}, {'id': 152, 'name': 'characterfield_practice_qualification', 'label': '执业资质', 'content_type': 8, 'object_id': 35}, {'id': 153, 'name': 'characterfield_password_setting', 'label': '密码设置', 'content_type': 8, 'object_id': 36}, {'id': 154, 'name': 'characterfield_confirm_password', 'label': '确认密码', 'content_type': 8, 'object_id': 37}, {'id': 155, 'name': 'characterfield_expertise', 'label': '专长', 'content_type': 8, 'object_id': 38}, {'id': 156, 'name': 'characterfield_practice_time', 'label': '执业时间', 'content_type': 8, 'object_id': 39}, {'id': 157, 'name': 'relatedfield_affiliation', 'label': '所属机构', 'content_type': 17, 'object_id': 64}, {'id': 158, 'name': 'datetimefield_date_of_birth', 'label': '出生日期', 'content_type': 13, 'object_id': 6}], 'managed_entity': []}, 
        {'id': 51, 'name': 'user_login', 'label': '用户登录', 'description': None, 'is_base_infomation': False, 'components': [{'id': 159, 'name': 'characterfield_username', 'label': '用户名', 'content_type': 8, 'object_id': 40}, {'id': 160, 'name': 'characterfield_password', 'label': '密码', 'content_type': 8, 'object_id': 41}], 'managed_entity': []}, 
        {'id': 52, 'name': 'doctor_login', 'label': '医生登陆', 'description': None, 'is_base_infomation': False, 'components': [{'id': 159, 'name': 'characterfield_username', 'label': '用户名', 'content_type': 8, 'object_id': 40}, {'id': 160, 'name': 'characterfield_password', 'label': '密码', 'content_type': 8, 'object_id': 41}, {'id': 161, 'name': 'characterfield_service_role', 'label': '服务角色', 'content_type': 8, 'object_id': 42}], 'managed_entity': []}, 
        {'id': 53, 'name': 'dorsal_artery_pulsation_examination', 'label': '足背动脉搏动检查', 'description': None, 'is_base_infomation': False, 'components': [{'id': 162, 'name': 'relatedfield_left_foot', 'label': '左脚', 'content_type': 17, 'object_id': 65}, {'id': 163, 'name': 'relatedfield_right_foot', 'label': '右脚', 'content_type': 17, 'object_id': 66}], 'managed_entity': []}, 
        {'id': 54, 'name': 'physical_examination_hearing', 'label': '查体听力', 'description': None, 'is_base_infomation': False, 'components': [{'id': 164, 'name': 'relatedfield_left_ear_hearing', 'label': '左耳听力', 'content_type': 17, 'object_id': 67}, {'id': 165, 'name': 'relatedfield_right_ear_hearing', 'label': '右耳听力', 'content_type': 17, 'object_id': 68}], 'managed_entity': []}, 
        {'id': 55, 'name': 'history_of_infectious_diseases', 'label': '遗传病史', 'description': None, 'is_base_infomation': False, 'components': [{'id': 135, 'name': 'relatedfield_diseases', 'label': '病名', 'content_type': 17, 'object_id': 59}, {'id': 136, 'name': 'relatedfield_family_relationship', 'label': '家庭成员关系', 'content_type': 17, 'object_id': 60}], 'managed_entity': []}, 
        {'id': 56, 'name': 'history_of_surgery', 'label': '手术史', 'description': None, 'is_base_infomation': False, 'components': [{'id': 140, 'name': 'datetimefield_date', 'label': '日期', 'content_type': 13, 'object_id': 4}, {'id': 166, 'name': 'relatedfield_name_of_operation', 'label': '手术名称', 'content_type': 17, 'object_id': 69}], 'managed_entity': []}, 
        {'id': 57, 'name': 'physical_examination_oral_cavity', 'label': '查体口腔', 'description': None, 'is_base_infomation': False, 'components': [{'id': 167, 'name': 'relatedfield_lips', 'label': '口唇', 'content_type': 17, 'object_id': 70}, {'id': 168, 'name': 'relatedfield_dentition', 'label': '齿列', 'content_type': 17, 'object_id': 71}, {'id': 169, 'name': 'relatedfield_pharynx', 'label': '咽部', 'content_type': 17, 'object_id': 72}], 'managed_entity': []}, 
        {'id': 58, 'name': 'blood_pressure_monitoring', 'label': '血压监测', 'description': None, 'is_base_infomation': False, 'components': [{'id': 170, 'name': 'numberfield_systolic_blood_pressure', 'label': '收缩压', 'content_type': 15, 'object_id': 19}, {'id': 171, 'name': 'numberfield_diastolic_blood_pressure', 'label': '舒张压', 'content_type': 15, 'object_id': 20}], 'managed_entity': []}, 
        {'id': 59, 'name': 'major_life_events', 'label': '重大生活事件调查', 'description': None, 'is_base_infomation': False, 'components': [{'id': 140, 'name': 'datetimefield_date', 'label': '日期', 'content_type': 13, 'object_id': 4}, {'id': 172, 'name': 'relatedfield_major_life', 'label': '生活事件', 'content_type': 17, 'object_id': 73}], 'managed_entity': []}, 
        {'id': 60, 'name': 'physical_examination_vision', 'label': '查体视力', 'description': None, 'is_base_infomation': False, 'components': [{'id': 173, 'name': 'characterfield_left_eye_vision', 'label': '左眼视力', 'content_type': 8, 'object_id': 43}, {'id': 174, 'name': 'characterfield_right_eye_vision', 'label': '右眼视力', 'content_type': 8, 'object_id': 44}], 'managed_entity': []}, 
        {'id': 61, 'name': 'lower_extremity_edema_examination', 'label': '下肢水肿检查', 'description': None, 'is_base_infomation': False, 'components': [{'id': 175, 'name': 'relatedfield_lower_extremity_edema', 'label': '下肢水肿', 'content_type': 17, 'object_id': 74}], 'managed_entity': []}, 
        {'id': 62, 'name': 'basic_personal_information', 'label': '个人基本情况', 'description': None, 'is_base_infomation': False, 'components': [{'id': 136, 'name': 'relatedfield_family_relationship', 'label': '家庭成员关系', 'content_type': 17, 'object_id': 60}, {'id': 145, 'name': 'characterfield_name', 'label': '姓名', 'content_type': 8, 'object_id': 29}, {'id': 148, 'name': 'characterfield_identification_number', 'label': '身份证号码', 'content_type': 8, 'object_id': 32}, {'id': 158, 'name': 'datetimefield_date_of_birth', 'label': '出生日期', 'content_type': 13, 'object_id': 6}, {'id': 176, 'name': 'relatedfield_family_id', 'label': '家庭编号', 'content_type': 17, 'object_id': 75}, {'id': 177, 'name': 'characterfield_resident_file_number', 'label': '居民档案号', 'content_type': 8, 'object_id': 45}, {'id': 178, 'name': 'relatedfield_gender', 'label': '性别', 'content_type': 17, 'object_id': 76}, {'id': 179, 'name': 'relatedfield_nationality', 'label': '民族', 'content_type': 17, 'object_id': 77}, {'id': 180, 'name': 'relatedfield_marital_status', 'label': '婚姻状况', 'content_type': 17, 'object_id': 78}, {'id': 181, 'name': 'relatedfield_education', 'label': '文化程度', 'content_type': 17, 'object_id': 79}, {'id': 182, 'name': 'relatedfield_occupational_status', 'label': '职业状况', 'content_type': 17, 'object_id': 80}, {'id': 183, 'name': 'characterfield_family_address', 'label': '家庭地址', 'content_type': 8, 'object_id': 46}, {'id': 184, 'name': 'characterfield_contact_number', 'label': '联系电话', 'content_type': 8, 'object_id': 47}, {'id': 185, 'name': 'characterfield_medical_ic_card_number', 'label': '医疗ic卡号', 'content_type': 8, 'object_id': 48}, {'id': 186, 'name': 'relatedfield_medical_expenses_burden', 'label': '医疗费用负担', 'content_type': 17, 'object_id': 81}, {'id': 187, 'name': 'relatedfield_type_of_residence', 'label': '居住类型', 'content_type': 17, 'object_id': 82}, {'id': 188, 'name': 'relatedfield_blood_type', 'label': '血型', 'content_type': 17, 'object_id': 83}, {'id': 189, 'name': 'boolfield_contract_signatory', 'label': '合同签约户', 'content_type': 7, 'object_id': 32}, {'id': 190, 'name': 'relatedfield_signed_family_doctor', 'label': '签约家庭医生', 'content_type': 17, 'object_id': 84}], 'managed_entity': []}, 
        {'id': 63, 'name': 'physical_examination_athletic_ability', 'label': '查体运动能力', 'description': None, 'is_base_infomation': False, 'components': [{'id': 191, 'name': 'relatedfield_athletic_ability', 'label': '运动能力', 'content_type': 17, 'object_id': 85}], 'managed_entity': []}, 
        {'id': 64, 'name': 'user_registry', 'label': '用户注册表', 'description': None, 'is_base_infomation': False, 'components': [{'id': 145, 'name': 'characterfield_name', 'label': '姓名', 'content_type': 8, 'object_id': 29}, {'id': 146, 'name': 'characterfield_gender', 'label': '性别', 'content_type': 8, 'object_id': 30}, {'id': 147, 'name': 'characterfield_age', 'label': '年龄', 'content_type': 8, 'object_id': 31}, {'id': 148, 'name': 'characterfield_identification_number', 'label': '身份证号码', 'content_type': 8, 'object_id': 32}, {'id': 149, 'name': 'characterfield_contact_information', 'label': '联系电话', 'content_type': 8, 'object_id': 33}, {'id': 150, 'name': 'characterfield_contact_address', 'label': '联系地址', 'content_type': 8, 'object_id': 34}, {'id': 153, 'name': 'characterfield_password_setting', 'label': '密码设置', 'content_type': 8, 'object_id': 36}, {'id': 154, 'name': 'characterfield_confirm_password', 'label': '确认密码', 'content_type': 8, 'object_id': 37}, {'id': 158, 'name': 'datetimefield_date_of_birth', 'label': '出生日期', 'content_type': 13, 'object_id': 6}], 'managed_entity': []}, 
        {'id': 65, 'name': 'men_zhen_wen_zhen_diao_cha_biao', 'label': '门诊问诊调查表', 'description': '', 'is_base_infomation': False, 'components': [{'id': 99, 'name': 'relatedfield_symptom_list', 'label': '症状', 'content_type': 17, 'object_id': 45}, {'id': 100, 'name': 'characterfield_supplementary_description_of_the_condition', 'label': '病情补充描述', 'content_type': 8, 'object_id': 25}], 'managed_entity': []}, 
        {'id': 66, 'name': 'kong_fu_xue_tang_jian_cha', 'label': '空腹血糖检查', 'description': '', 'is_base_infomation': False, 'components': [{'id': 192, 'name': 'numberfield_kong_fu_xue_tang', 'label': '空腹血糖', 'content_type': 15, 'object_id': 21}], 'managed_entity': []}, 
        {'id': 67, 'name': 'tang_hua_xue_hong_dan_bai_jian_cha_biao', 'label': '糖化血红蛋白检查表', 'description': '', 'is_base_infomation': False, 'components': [{'id': 193, 'name': 'numberfield_tang_hua_xue_hong_dan_bai', 'label': '糖化血红蛋白', 'content_type': 15, 'object_id': 22}], 'managed_entity': []}, 
        {'id': 68, 'name': 'men_zhen_zhen_duan_biao', 'label': '门诊诊断表', 'description': '', 'is_base_infomation': False, 'components': [{'id': 142, 'name': 'relatedfield_disease_name', 'label': '疾病名称', 'content_type': 17, 'object_id': 61}], 'managed_entity': []}, 
        {'id': 69, 'name': 'yong_yao_chu_fang', 'label': '用药处方', 'description': '', 'is_base_infomation': False, 'components': [{'id': 98, 'name': 'relatedfield_drug_name', 'label': '药品名称', 'content_type': 17, 'object_id': 44}], 'managed_entity': []}
    ],

    'baseforms': [
        {'id': 66, 'name': 'basic_personal_information_baseform_query_1642159528', 'label': '个人基本情况_查询视图_1642159528', 'basemodel': 'basic_personal_information', 'is_inquiry': True, 'style': 'detail', 'components': [{'id': 145, 'name': 'characterfield_name', 'label': '姓名', 'content_type': 8, 'object_id': 29}, {'id': 158, 'name': 'datetimefield_date_of_birth', 'label': '出生日期', 'content_type': 13, 'object_id': 6}, {'id': 178, 'name': 'relatedfield_gender', 'label': '性别', 'content_type': 17, 'object_id': 76}, {'id': 184, 'name': 'characterfield_contact_number', 'label': '联系电话', 'content_type': 8, 'object_id': 47}]}, 
        {'id': 71, 'name': 'out_of_hospital_self_report_survey_baseform_query_1642212281', 'label': '院外症状自述调查_查询视图_1642212281', 'basemodel': 'out_of_hospital_self_report_survey', 'is_inquiry': True, 'style': 'detail', 'components': [{'id': 99, 'name': 'relatedfield_symptom_list', 'label': '症状', 'content_type': 17, 'object_id': 45}, {'id': 100, 'name': 'characterfield_supplementary_description_of_the_condition', 'label': '病情补充描述', 'content_type': 8, 'object_id': 25}]},
    ],

    'combineforms': [
        {'id': 82, 'name': 'yuan_qian_zheng_zhuang_diao_cha_biao', 'label': '院前症状调查表', 'is_base': False, 'managed_entity': None, 'forms': ['out_of_hospital_self_report_survey_baseform', 'basic_personal_information_baseform_query_1642159528', 'men_zhen_wen_zhen_biao']}, 
        {'id': 83, 'name': 'ge_ren_ji_bing_shi_diao_cha_biao', 'label': '个人疾病史调查表', 'is_base': False, 'managed_entity': None, 'forms': ['medical_history_baseform', 'basic_personal_information_baseform_query_1642159528']}, 
        {'id': 85, 'name': 'men_zhen_wen_zhen_biao', 'label': '门诊问诊表', 'is_base': False, 'managed_entity': None, 'forms': ['basic_personal_information_baseform_query_1642159528', 'yuan_qian_zheng_zhuang_diao_cha_biao']}, 
        {'id': 88, 'name': 'kong_fu_xue_tang_jian_cha_biao', 'label': '空腹血糖检查表', 'is_base': False, 'managed_entity': None, 'forms': ['basic_personal_information_baseform_query_1642159528', 'kong_fu_xue_tang_jian_cha_baseform']}, 
        {'id': 90, 'name': 'men_zhen_zhen_duan_biao_1', 'label': '门诊诊断表1', 'is_base': False, 'managed_entity': None, 'forms': ['basic_personal_information_baseform_query_1642159528', 'men_zhen_zhen_duan_biao_baseform']}, 
        {'id': 91, 'name': 'tang_hua_xue_hong_dan_bai_jian_cha_biao_1', 'label': '糖化血红蛋白检查表1', 'is_base': False, 'managed_entity': None, 'forms': ['basic_personal_information_baseform_query_1642159528', 'tang_hua_xue_hong_dan_bai_jian_cha_biao_baseform']}, 
        {'id': 92, 'name': 'guo_min_shi_diao_cha_biao', 'label': '过敏史调查表', 'is_base': False, 'managed_entity': None, 'forms': ['allergies_history_baseform', 'basic_personal_information_baseform_query_1642159528']}, 
        {'id': 93, 'name': 'tang_niao_bing_cha_ti_biao', 'label': '糖尿病查体表', 'is_base': False, 'managed_entity': None, 'forms': ['fundus_examination_baseform', 'dorsal_artery_pulsation_examination_baseform', 'basic_personal_information_baseform_query_1642159528']}, 
        {'id': 94, 'name': 'chang_gui_cha_ti_biao', 'label': '常规查体表', 'is_base': False, 'managed_entity': None, 'forms': ['vital_signs_check_baseform', 'physical_examination_baseform', 'physical_examination_hearing_baseform', 'physical_examination_oral_cavity_baseform', 'physical_examination_vision_baseform', 'physical_examination_athletic_ability_baseform', 'basic_personal_information_baseform_query_1642159528']}, 
        {'id': 98, 'name': 'men_zhen_chu_fang_dan', 'label': '门诊处方单', 'is_base': False, 'managed_entity': None, 'forms': ['basic_personal_information_baseform_query_1642159528', 'yong_yao_chu_fang_baseform']}
    ],

    'operandviews': [
        {'id': 15, 'name': 'yuan_qian_zheng_zhuang_diao_cha_biao', 'label': '院前症状调查表', 'managed_entity': None, 'forms': 'yuan_qian_zheng_zhuang_diao_cha_biao'}, 
        {'id': 17, 'name': 'ge_ren_ji_bing_shi_diao_cha_biao', 'label': '个人疾病史调查表', 'managed_entity': None, 'forms': 'ge_ren_ji_bing_shi_diao_cha_biao'}, 
        {'id': 18, 'name': 'kong_fu_xue_tang_jian_cha_biao', 'label': '空腹血糖检查表', 'managed_entity': None, 'forms': 'kong_fu_xue_tang_jian_cha_biao'}, 
        {'id': 19, 'name': 'men_zhen_zhen_duan_biao', 'label': '门诊诊断表', 'managed_entity': None, 'forms': 'men_zhen_zhen_duan_biao_1'}, 
        {'id': 20, 'name': 'tang_hua_xue_hong_dan_bai_jian_cha_biao', 'label': '糖化血红蛋白检查表', 'managed_entity': None, 'forms': 'tang_hua_xue_hong_dan_bai_jian_cha_biao_1'}, 
        {'id': 21, 'name': 'chang_gui_cha_ti_biao', 'label': '常规查体表', 'managed_entity': None, 'forms': 'chang_gui_cha_ti_biao'}, 
        {'id': 22, 'name': 'tang_niao_bing_cha_ti_biao', 'label': '糖尿病查体表', 'managed_entity': None, 'forms': 'tang_niao_bing_cha_ti_biao'}, 
        {'id': 23, 'name': 'ge_ren_guo_min_shi_diao_cha_biao', 'label': '个人过敏史调查表', 'managed_entity': None, 'forms': 'guo_min_shi_diao_cha_biao'}, 
        {'id': 25, 'name': 'men_zhen_chu_fang_biao', 'label': '门诊处方表', 'managed_entity': None, 'forms': 'men_zhen_chu_fang_dan'},
    ],
}