version: "3"

networks:
  web:
    external: true

services:
  app:
    image: jinniudashu/design-clinic:v1
    container_name: design-clinic
    command: 
      - sh
      - -c
      - |
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - app:/app/
    env_file:
      - ./.env
    networks:
      - web
    labels:
      - "traefik.enable=true" # <== Enable traefik on itself to view dashboard and assign subdomain to view it
      - "traefik.http.routers.clinic-http.rule=Host(`design-clinic.tpacn.com`)" # <== Setting the domain for the dashboard
      - "traefik.http.routers.clinic-http.entrypoints=web" # <== Enabling the entrypoint for the whoami service
      - "traefik.http.services.clinic-http.loadbalancer.server.port=8000" # <== Enabling the port for the whoami service

volumes:
  app: