# Generated by Django 4.0 on 2022-03-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_rule_dict', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventrule',
            options={'ordering': ['id'], 'verbose_name': '条件事件', 'verbose_name_plural': '条件事件'},
        ),
        migrations.AlterField(
            model_name='eventexpression',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='eventrule',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='frequencyrule',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='intervalrule',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
    ]
