# Generated by Django 4.0 on 2022-03-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_rule_dict', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventexpression',
            old_name='icpc_field',
            new_name='field',
        ),
        migrations.AlterField(
            model_name='eventrule',
            name='expression',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='表达式'),
        ),
    ]
