# Generated by Django 4.0 on 2022-03-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_rule_dict', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventexpression',
            name='event_expression_id',
        ),
        migrations.RemoveField(
            model_name='eventrule',
            name='event_rule_id',
        ),
        migrations.RemoveField(
            model_name='frequencyrule',
            name='frequency_rule_id',
        ),
        migrations.RemoveField(
            model_name='frequencyrule',
            name='label',
        ),
        migrations.RemoveField(
            model_name='frequencyrule',
            name='name',
        ),
        migrations.RemoveField(
            model_name='intervalrule',
            name='label',
        ),
        migrations.RemoveField(
            model_name='intervalrule',
            name='name',
        ),
        migrations.RemoveField(
            model_name='intervalrule',
            name='operand_interval_rule_id',
        ),
        migrations.AddField(
            model_name='eventexpression',
            name='hssc_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID'),
        ),
        migrations.AddField(
            model_name='eventexpression',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='eventexpression',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='eventrule',
            name='hssc_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID'),
        ),
    ]
