# Generated by Django 4.0 on 2022-03-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_rule_dict', '0002_remove_eventexpression_event_expression_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencyrule',
            name='hssc_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID'),
        ),
        migrations.AddField(
            model_name='frequencyrule',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='frequencyrule',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='intervalrule',
            name='hssc_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID'),
        ),
        migrations.AddField(
            model_name='intervalrule',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='intervalrule',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
    ]
