# Generated by Django 4.0 on 2022-03-25 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_operand', '0007_servicespec_and_more'),
        ('define_rule_dict', '0002_servicespec'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceSpec',
        ),
    ]
