# Generated by Django 4.0 on 2021-12-08 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='视图名称')),
                ('is_inquiry', models.BooleanField(default=False, verbose_name='仅用于查询')),
                ('style', models.CharField(choices=[('detail', '详情'), ('list', '列表')], default='detail', max_length=50, verbose_name='风格')),
                ('display_fields', models.TextField(blank=True, max_length=1024, null=True, verbose_name='表单字段')),
            ],
            options={
                'verbose_name': '基础视图',
                'verbose_name_plural': '基础视图',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CharacterField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='name')),
                ('label', models.CharField(max_length=100, verbose_name='组件名称')),
                ('type', models.CharField(choices=[('CharField', '单行文本'), ('TextField', '多行文本')], default='CharField', max_length=50, verbose_name='类型')),
                ('length', models.PositiveSmallIntegerField(default=255, verbose_name='字符长度')),
                ('required', models.BooleanField(default=False, verbose_name='必填')),
                ('default', models.CharField(blank=True, max_length=255, null=True, verbose_name='默认值')),
            ],
            options={
                'verbose_name': '字符字段',
                'verbose_name_plural': '字符字段',
            },
        ),
        migrations.CreateModel(
            name='ChoiceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='name')),
                ('label', models.CharField(max_length=100, verbose_name='组件名称')),
                ('type', models.CharField(choices=[('Select', '下拉单选'), ('RadioSelect', '单选按钮列表'), ('CheckboxSelectMultiple', '复选框列表'), ('SelectMultiple', '下拉多选')], default='ChoiceField', max_length=50, verbose_name='类型')),
                ('options', models.TextField(blank=True, help_text='每行一个选项, 最多100个', max_length=1024, null=True, verbose_name='选项')),
                ('default_first', models.BooleanField(default=False, verbose_name='默认选第一个')),
                ('required', models.BooleanField(default=False, verbose_name='必填')),
            ],
            options={
                'verbose_name': '选择字段',
                'verbose_name_plural': '选择字段',
            },
        ),
        migrations.CreateModel(
            name='ComputeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DTField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='name')),
                ('label', models.CharField(max_length=100, verbose_name='组件名称')),
                ('type', models.CharField(choices=[('DateTimeField', '日期时间'), ('DateField', '日期')], default='DateTimeField', max_length=50, verbose_name='类型')),
                ('default_now', models.BooleanField(default=False, verbose_name='默认为当前时间')),
                ('required', models.BooleanField(default=False, verbose_name='必填')),
            ],
            options={
                'verbose_name': '日期字段',
                'verbose_name_plural': '日期字段',
            },
        ),
        migrations.CreateModel(
            name='NumberField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='name')),
                ('label', models.CharField(max_length=100, verbose_name='组件名称')),
                ('type', models.CharField(choices=[('IntegerField', '整数'), ('DecimalField', '固定精度小数'), ('FloatField', '浮点数')], default='IntegerField', max_length=50, verbose_name='类型')),
                ('max_digits', models.PositiveSmallIntegerField(blank=True, default=10, null=True, verbose_name='最大位数')),
                ('decimal_places', models.PositiveSmallIntegerField(blank=True, default=2, null=True, verbose_name='小数位数')),
                ('standard_value', models.FloatField(blank=True, null=True, verbose_name='标准值')),
                ('up_limit', models.FloatField(blank=True, null=True, verbose_name='上限')),
                ('down_limit', models.FloatField(blank=True, null=True, verbose_name='下限')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='单位')),
                ('default', models.FloatField(blank=True, null=True, verbose_name='默认值')),
                ('required', models.BooleanField(default=False, verbose_name='必填')),
            ],
            options={
                'verbose_name': '数值字段',
                'verbose_name_plural': '数值字段',
            },
        ),
        migrations.CreateModel(
            name='RelatedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='name')),
                ('label', models.CharField(max_length=100, verbose_name='组件名称')),
                ('type', models.CharField(choices=[('Select', '下拉单选'), ('RadioSelect', '单选按钮列表'), ('CheckboxSelectMultiple', '复选框列表'), ('SelectMultiple', '下拉多选')], default='ChoiceField', max_length=50, verbose_name='类型')),
                ('related_field', models.CharField(blank=True, max_length=100, null=True, verbose_name='关联字段')),
                ('related_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '关联字段',
                'verbose_name_plural': '关联字段',
            },
        ),
        migrations.CreateModel(
            name='OperandView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='表单名称')),
                ('axis_field', models.CharField(choices=[('customer', '客户'), ('staff', '员工'), ('medicine', '药品'), ('device', '设备')], default='customer', max_length=255, verbose_name='业务主键')),
                ('inquire_forms', models.ManyToManyField(blank=True, limit_choices_to={'is_inquiry': True}, null=True, related_name='inquire_forms', to='define.BaseForm', verbose_name='查询视图')),
                ('mutate_forms', models.ManyToManyField(limit_choices_to={'is_inquiry': False}, related_name='mutate_forms', to='define.BaseForm', verbose_name='变更视图')),
            ],
            options={
                'verbose_name': '作业界面',
                'verbose_name_plural': '作业界面',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='name')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='组件名称')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'customized_forms'), models.Q(('model', 'characterfield'), ('model', 'numberfield'), ('model', 'dtfield'), ('model', 'choicefield'), ('model', 'relatedfield'), ('model', 'computefield'), _connector='OR')), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '字段字典',
                'verbose_name_plural': '字段字典',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='表单名称')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('components', models.ManyToManyField(to='define.Component', verbose_name='组件清单')),
            ],
            options={
                'verbose_name': '基础表单',
                'verbose_name_plural': '基础表单',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='baseform',
            name='basemodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='define.basemodel', verbose_name='基础表单'),
        ),
        migrations.AddField(
            model_name='baseform',
            name='components',
            field=models.ManyToManyField(to='define.Component', verbose_name='组件清单'),
        ),
    ]
