# Generated by Django 4.0 on 2021-12-08 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('define', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'define'), models.Q(('model', 'characterfield'), ('model', 'numberfield'), ('model', 'dtfield'), ('model', 'choicefield'), ('model', 'relatedfield'), ('model', 'computefield'), _connector='OR')), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
