# Generated by Django 4.0 on 2022-02-27 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('define', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatefieldmodel',
            name='name_icpc',
        ),
        migrations.AlterField(
            model_name='relatefieldmodel',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'define_dict'), models.Q(('model', 'diclist'), ('model', 'managedentity'), _connector='OR')), ('app_label', 'define_icpc'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='关联基本信息'),
        ),
    ]
