# Generated by Django 4.0 on 2022-01-28 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseform',
            name='basemodel',
        ),
        migrations.RemoveField(
            model_name='baseform',
            name='components',
        ),
        migrations.RemoveField(
            model_name='basemodel',
            name='components',
        ),
        migrations.RemoveField(
            model_name='basemodel',
            name='managed_entity',
        ),
        migrations.RemoveField(
            model_name='combineform',
            name='forms',
        ),
        migrations.RemoveField(
            model_name='combineform',
            name='managed_entity',
        ),
        migrations.RemoveField(
            model_name='operandview',
            name='forms',
        ),
        migrations.RemoveField(
            model_name='operandview',
            name='managed_entity',
        ),
        migrations.DeleteModel(
            name='SourceCode',
        ),
        migrations.DeleteModel(
            name='BaseForm',
        ),
        migrations.DeleteModel(
            name='BaseModel',
        ),
        migrations.DeleteModel(
            name='CombineForm',
        ),
        migrations.DeleteModel(
            name='ManagedEntity',
        ),
        migrations.DeleteModel(
            name='OperandView',
        ),
    ]
