# Generated by Django 4.0 on 2022-03-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diclist',
            options={'verbose_name': '自定义关联字典', 'verbose_name_plural': '自定义关联字典'},
        ),
    ]
