# Generated by Django 4.0 on 2022-03-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='name')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='组件名称')),
                ('components_group_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='组件ID')),
                ('components', models.ManyToManyField(to='define.Component', verbose_name='字段')),
            ],
            options={
                'verbose_name': '组件',
                'verbose_name_plural': '组件',
            },
        ),
    ]
