# Generated by Django 4.0 on 2022-03-28 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dicdetail',
            old_name='item',
            new_name='value',
        ),
    ]
