# Generated by Django 4.0 on 2022-05-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medcine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YPCode', models.CharField(max_length=255, verbose_name='药品编码')),
                ('PYM', models.CharField(max_length=255, verbose_name='拼音码')),
                ('YPName', models.CharField(max_length=255, verbose_name='药品名称')),
            ],
            options={
                'verbose_name': '药品基本信息',
                'verbose_name_plural': '药品基本信息',
                'ordering': ['id'],
            },
        ),
    ]
