# Generated by Django 4.0 on 2022-05-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterfield',
            name='required',
        ),
        migrations.RemoveField(
            model_name='dtfield',
            name='required',
        ),
        migrations.RemoveField(
            model_name='numberfield',
            name='required',
        ),
    ]
