# Generated by Django 4.0 on 2022-10-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YPCode', models.CharField(max_length=10, verbose_name='药品编码')),
                ('PYM', models.CharField(max_length=100, null=True, verbose_name='拼音码')),
                ('YPName', models.CharField(max_length=200, null=True, verbose_name='药品名称')),
                ('Specification', models.CharField(max_length=100, null=True, verbose_name='规格')),
                ('Measure', models.CharField(max_length=30, null=True, verbose_name='单位')),
                ('MZPrice', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='门诊参考单价')),
                ('Usage', models.CharField(max_length=60, null=True, verbose_name='用法')),
                ('Dosage', models.CharField(max_length=60, null=True, verbose_name='用量')),
                ('Type', models.CharField(max_length=40, null=True, verbose_name='药剂类型')),
                ('YPSort', models.CharField(max_length=60, null=True, verbose_name='药品分类名称')),
                ('MaxStorage', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='最大库存')),
                ('MinStorage', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='最小库存')),
                ('CurrentStorage', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='当前库存')),
                ('CFMeasure', models.CharField(max_length=30, null=True, verbose_name='处方计量单位')),
                ('XSMeasure', models.CharField(max_length=30, null=True, verbose_name='销售计量单位')),
                ('RK2XS', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='计量单位换算（入库销售）')),
                ('XS2CF', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='计量单位换算（销售处方）')),
                ('AllowBreak', models.BooleanField(default=False, verbose_name='允许拆散销售')),
                ('PricePercentLS', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='拆散零售价制定比例')),
                ('PricePercentXS', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='正常销售价制定比例')),
                ('EconomyBatch', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='经济批量')),
                ('MinBuy', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='最小订货量')),
                ('CountForCode', models.CharField(max_length=10, null=True, verbose_name='价值分类码')),
                ('CFDosage', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='常用单次处方用量(处方单位)')),
                ('NotCFYP', models.BooleanField(default=False, verbose_name='非处方药标记')),
                ('IsSurveillant', models.BooleanField(default=False, verbose_name='是否为监测使用')),
                ('Cycle', models.BooleanField(default=False, verbose_name='循环盘点标志')),
                ('LastCycleDate', models.DateTimeField(null=True, verbose_name='上次盘点时间')),
                ('Anaphylaxis', models.BooleanField(default=False, verbose_name='药品过敏标识')),
                ('isXY', models.BooleanField(default=False, verbose_name='为西药')),
                ('isAppliance', models.BooleanField(default=False, verbose_name='为医用器材(耗材)')),
                ('isCHN', models.BooleanField(default=False, verbose_name='为中药药材')),
                ('isNew', models.BooleanField(default=False, verbose_name='新药标识')),
                ('WJH', models.CharField(max_length=50, null=True, verbose_name='存放货架号')),
                ('CFCM', models.CharField(max_length=30, null=True, verbose_name='存放的层位码')),
                ('MZPriceCF', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='门诊处方价格')),
                ('IsUse', models.BooleanField(default=True, verbose_name='是否使用中')),
                ('YptyName', models.CharField(max_length=200, null=True, verbose_name='药品通用名称')),
                ('gjjbyp', models.CharField(max_length=100, null=True, verbose_name='国家基本药品目录名称')),
                ('ybypbm', models.CharField(max_length=100, null=True, verbose_name='医保药品目录对应药品编码')),
                ('ybyplb', models.CharField(max_length=2, null=True, verbose_name='药品报销类别（甲类、乙类）')),
            ],
            options={
                'verbose_name': '药品基本信息导入表',
                'verbose_name_plural': '药品基本信息导入表',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
