# Generated by Django 4.0 on 2022-03-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['id'], 'verbose_name': '业务字段汇总', 'verbose_name_plural': '业务字段汇总'},
        ),
        migrations.AlterModelOptions(
            name='dicdetail',
            options={'verbose_name': '业务字典明细', 'verbose_name_plural': '业务字典明细'},
        ),
        migrations.AlterModelOptions(
            name='diclist',
            options={'verbose_name': '业务字典列表', 'verbose_name_plural': '业务字典列表'},
        ),
        migrations.AlterModelOptions(
            name='managedentity',
            options={'verbose_name': '业务管理实体', 'verbose_name_plural': '业务管理实体'},
        ),
    ]
