# Generated by Django 4.0 on 2022-02-17 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('define_dict', '0001_initial'),
        ('define', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedfield',
            name='related_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='define_dict.diclist', verbose_name='关联内容-旧版'),
        ),
        migrations.CreateModel(
            name='RelateFieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('label', models.CharField(max_length=100, verbose_name='关联模型名称')),
                ('related_content', models.CharField(blank=True, max_length=100, null=True, verbose_name='关联内容')),
                ('display_field', models.CharField(blank=True, max_length=100, null=True, verbose_name='显示字段')),
                ('related_field', models.CharField(blank=True, max_length=100, null=True, verbose_name='关联字段')),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'define_icpc'), models.Q(('model', 'icpcbackup'), _negated=True)), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='关联基本信息')),
                ('related_dict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_dict.diclist', verbose_name='关联字典')),
            ],
            options={
                'verbose_name': '关联字段表',
                'verbose_name_plural': '关联字段表',
            },
        ),
        migrations.AddField(
            model_name='relatedfield',
            name='related_conten_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define.relatefieldmodel', verbose_name='关联内容'),
        ),
    ]
