# Generated by Django 4.0 on 2022-05-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0002_medcine'),
    ]

    operations = [
        migrations.AddField(
            model_name='medcine',
            name='AllowBreak',
            field=models.BooleanField(default=False, verbose_name='允许拆散销售'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='Anaphylaxis',
            field=models.BooleanField(default=False, verbose_name='药品过敏标识'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='CFCM',
            field=models.CharField(max_length=30, null=True, verbose_name='存放的层位码'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='CFDosage',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='常用单次处方用量(处方单位)'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='CFMeasure',
            field=models.CharField(max_length=30, null=True, verbose_name='处方计量单位'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='CountForCode',
            field=models.CharField(max_length=10, null=True, verbose_name='价值分类码'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='CurrentStorage',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='当前库存'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='Cycle',
            field=models.BooleanField(default=False, verbose_name='循环盘点标志'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='Dosage',
            field=models.CharField(max_length=60, null=True, verbose_name='用量'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='EconomyBatch',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='经济批量'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='IsSurveillant',
            field=models.BooleanField(default=False, verbose_name='是否为监测使用'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='IsUse',
            field=models.BooleanField(default=True, verbose_name='是否使用中'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='LastCycleDate',
            field=models.DateTimeField(null=True, verbose_name='上次盘点时间'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='MZPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='门诊参考单价'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='MZPriceCF',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='门诊处方价格'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='MaxStorage',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='最大库存'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='Measure',
            field=models.CharField(max_length=30, null=True, verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='MinBuy',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='最小订货量'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='MinStorage',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='最小库存'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='NotCFYP',
            field=models.BooleanField(default=False, verbose_name='非处方药标记'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='PricePercentLS',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='拆散零售价制定比例'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='PricePercentXS',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='正常销售价制定比例'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='RK2XS',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='计量单位换算（入库销售）'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='Specification',
            field=models.CharField(max_length=100, null=True, verbose_name='规格'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='Type',
            field=models.CharField(max_length=40, null=True, verbose_name='药剂类型'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='Usage',
            field=models.CharField(max_length=60, null=True, verbose_name='用法'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='WJH',
            field=models.CharField(max_length=50, null=True, verbose_name='存放货架号'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='XS2CF',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='计量单位换算（销售处方）'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='XSMeasure',
            field=models.CharField(max_length=30, null=True, verbose_name='销售计量单位'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='YPSort',
            field=models.CharField(max_length=60, null=True, verbose_name='药品分类名称'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='YptyName',
            field=models.CharField(max_length=200, null=True, verbose_name='药品通用名称'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='gjjbyp',
            field=models.CharField(max_length=100, null=True, verbose_name='国家基本药品目录名称'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='isAppliance',
            field=models.BooleanField(default=False, verbose_name='为医用器材(耗材)'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='isCHN',
            field=models.BooleanField(default=False, verbose_name='为中药药材'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='isNew',
            field=models.BooleanField(default=False, verbose_name='新药标识'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='isXY',
            field=models.BooleanField(default=False, verbose_name='为西药'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='ybypbm',
            field=models.CharField(max_length=100, null=True, verbose_name='医保药品目录对应药品编码'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='ybyplb',
            field=models.CharField(max_length=2, null=True, verbose_name='药品报销类别（甲类、乙类）'),
        ),
        migrations.AlterField(
            model_name='medcine',
            name='PYM',
            field=models.CharField(max_length=100, null=True, verbose_name='拼音码'),
        ),
        migrations.AlterField(
            model_name='medcine',
            name='YPCode',
            field=models.CharField(max_length=10, verbose_name='药品编码'),
        ),
        migrations.AlterField(
            model_name='medcine',
            name='YPName',
            field=models.CharField(max_length=200, null=True, verbose_name='药品名称'),
        ),
    ]
