# Generated by Django 4.0 on 2022-10-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0002_medicineimport_delete_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('yp_code', models.CharField(max_length=10, verbose_name='药品编码')),
                ('specification', models.CharField(max_length=100, null=True, verbose_name='规格')),
                ('measure', models.CharField(max_length=30, null=True, verbose_name='单位')),
                ('mz_price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='门诊参考单价')),
                ('usage', models.CharField(max_length=60, null=True, verbose_name='用法')),
                ('dosage', models.CharField(max_length=60, null=True, verbose_name='用量')),
                ('type', models.CharField(max_length=40, null=True, verbose_name='药剂类型')),
                ('yp_sort', models.CharField(max_length=60, null=True, verbose_name='药品分类名称')),
                ('current_storage', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='当前库存')),
                ('cf_measure', models.CharField(max_length=30, null=True, verbose_name='处方计量单位')),
                ('xs_measure', models.CharField(max_length=30, null=True, verbose_name='销售计量单位')),
                ('cf_dosage', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='常用单次处方用量(处方单位)')),
                ('not_cfyp', models.BooleanField(default=False, verbose_name='非处方药标记')),
                ('mzcf_price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='门诊处方价格')),
                ('is_use', models.BooleanField(default=True, verbose_name='是否使用中')),
                ('ypty_name', models.CharField(max_length=200, null=True, verbose_name='药品通用名称')),
                ('gjjbyp', models.CharField(max_length=100, null=True, verbose_name='国家基本药品目录名称')),
                ('ybypbm', models.CharField(max_length=100, null=True, verbose_name='医保药品目录对应药品编码')),
                ('ybyplb', models.CharField(max_length=2, null=True, verbose_name='药品报销类别（甲类、乙类）')),
            ],
            options={
                'verbose_name': '药品基本信息表',
                'verbose_name_plural': '药品基本信息表',
                'ordering': ['id'],
            },
        ),
    ]
