# Generated by Django 4.0 on 2022-03-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0002_alter_boolfield_label_alter_characterfield_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentsgroup',
            name='pym',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码'),
        ),
        migrations.AddField(
            model_name='managedentity',
            name='pym',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码'),
        ),
        migrations.AlterField(
            model_name='component',
            name='pym',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码'),
        ),
        migrations.AlterField(
            model_name='diclist',
            name='pym',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码'),
        ),
    ]
