# Generated by Django 4.0 on 2021-12-31 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0002_alter_inquireform_options_alter_mutateform_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquireform',
            name='addforms',
        ),
        migrations.AddField(
            model_name='inquireform',
            name='inquireforms',
            field=models.ManyToManyField(blank=True, to='define.InquireForm', verbose_name='已有的组合查询视图'),
        ),
        migrations.AddField(
            model_name='mutateform',
            name='mutateforms',
            field=models.ManyToManyField(blank=True, to='define.MutateForm', verbose_name='已有的组合变更视图'),
        ),
    ]
