# Generated by Django 4.0 on 2021-12-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0002_alter_component_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoolField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='name')),
                ('label', models.CharField(max_length=100, verbose_name='组件名称')),
                ('available_choice', models.CharField(choices=[('0', '是, 否'), ('1', '未知, 是, 否')], default='0', max_length=100, verbose_name='可选值')),
                ('required', models.BooleanField(default=False, verbose_name='必填')),
                ('default', models.CharField(blank=True, max_length=255, null=True, verbose_name='默认值')),
            ],
            options={
                'verbose_name': '是否字段',
                'verbose_name_plural': '是否字段',
            },
        ),
        migrations.AlterField(
            model_name='baseform',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='operandview',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
    ]
