# Generated by Django 4.0 on 2022-03-25 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('define', '0002_alter_component_content_type_delete_boolfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedentity',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'define_operand'), ('model', 'buessinessform')), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='managedentity',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
