# Generated by Django 4.0 on 2023-08-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0002_rename_gjjbyp_medicineimport_gjjbyp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='cf_dosage',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='current_storage',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='fytj',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='is_use',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='measure',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='mzcf_price',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='not_cfyp',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='xs_measure',
        ),
        migrations.AddField(
            model_name='medicine',
            name='blfy',
            field=models.CharField(max_length=255, null=True, verbose_name='不良反应'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='ypglsx',
            field=models.CharField(max_length=60, null=True, verbose_name='药品管理属性'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='cf_measure',
            field=models.CharField(max_length=30, null=True, verbose_name='处方剂量单位'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dosage',
            field=models.CharField(max_length=60, null=True, verbose_name='常用剂量'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='fyzysxhbz',
            field=models.CharField(max_length=255, null=True, verbose_name='用药备注'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='usage',
            field=models.CharField(max_length=60, null=True, verbose_name='用药途径'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='ybyplb',
            field=models.CharField(max_length=2, null=True, verbose_name='医保报销类别'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='yp_sort',
            field=models.CharField(max_length=60, null=True, verbose_name='药品分类'),
        ),
    ]
