# Generated by Django 4.0 on 2022-05-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0002_remove_characterfield_required_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medcine',
            new_name='Medicine',
        ),
        migrations.AlterField(
            model_name='relatefieldmodel',
            name='related_content_type',
            field=models.CharField(choices=[('dictionaries', '基础字典'), ('icpc', 'ICPC'), ('service', '管理实体'), ('core', '内核')], default=0, max_length=20, verbose_name='关联内容类型'),
        ),
    ]
