# Generated by Django 4.0 on 2022-02-18 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('define', '0002_alter_relatedfield_related_content_relatefieldmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatefieldmodel',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'define_icpc'), models.Q(('model', 'icpcbackup'), _negated=True)), models.Q(('app_label', 'define_operand'), ('model', 'role')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='关联基本信息'),
        ),
    ]
