# Generated by Django 4.0 on 2022-01-28 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_dict', '0001_initial'),
        ('define', '0002_remove_baseform_basemodel_remove_baseform_components_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['id'], 'verbose_name': '字段列表', 'verbose_name_plural': '字段列表'},
        ),
        migrations.AlterField(
            model_name='relatedfield',
            name='related_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='define_dict.diclist', verbose_name='关联内容'),
        ),
        migrations.DeleteModel(
            name='DicList',
        ),
    ]
