# Generated by Django 4.0 on 2022-02-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0002_remove_relatefieldmodel_name_icpc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatefieldmodel',
            name='relate_field_model_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='关联字段基础表ID'),
        ),
    ]
