# Generated by Django 4.0 on 2022-03-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0002_componentsgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='pym',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='拼音码'),
        ),
    ]
