# Generated by Django 4.0 on 2022-02-18 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0003_alter_relatefieldmodel_content_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatedfield',
            old_name='related_conten_new',
            new_name='related_content_new',
        ),
    ]
