# Generated by Django 4.0 on 2022-03-26 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0003_managedentity_content_type_managedentity_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managedentity',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='managedentity',
            name='object_id',
        ),
    ]
