# Generated by Django 4.0 on 2021-12-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0003_remove_inquireform_addforms_inquireform_inquireforms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseform',
            name='display_fields',
        ),
        migrations.AddField(
            model_name='baseform',
            name='fields',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='视图字段'),
        ),
    ]
