# Generated by Django 4.0 on 2023-09-07 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_icpc', '0001_initial'),
        ('define', '0003_remove_medicine_cf_dosage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemReservedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hssc_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='hsscID')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('label', models.CharField(max_length=63, null=True, verbose_name='名称')),
                ('name', models.CharField(blank=True, max_length=63, null=True, verbose_name='name')),
                ('type', models.CharField(choices=[('charge_staff', '责任人'), ('operator', '作业人员'), ('scheduled_time', '计划执行时间'), ('duration', '时长'), ('frequency', '频次')], default='ImageField', max_length=50, verbose_name='类型')),
                ('name_icpc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_icpc.icpc', verbose_name='ICPC编码')),
            ],
            options={
                'verbose_name': '系统字段',
                'verbose_name_plural': '系统字段',
            },
        ),
    ]
