# Generated by Django 4.0 on 2022-02-19 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('define', '0004_rename_related_conten_new_relatedfield_related_content_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatefieldmodel',
            name='related_dict',
        ),
        migrations.AddField(
            model_name='relatefieldmodel',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relatefieldmodel',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'define_dict'), ('model', 'diclist')), models.Q(('app_label', 'define_form'), ('model', 'managedentity')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='关联基本信息'),
        ),
    ]
