# Generated by Django 4.0 on 2021-12-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0004_remove_baseform_display_fields_baseform_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquireform',
            name='fields',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='视图字段'),
        ),
        migrations.AddField(
            model_name='mutateform',
            name='fields',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='视图字段'),
        ),
        migrations.AddField(
            model_name='operandview',
            name='fields',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='视图字段'),
        ),
    ]
