# Generated by Django 4.0 on 2023-09-09 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0004_systemreservedfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemreservedfield',
            options={'verbose_name': '系统API字段', 'verbose_name_plural': '系统API字段'},
        ),
    ]
