# Generated by Django 4.0 on 2021-12-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0004_alter_boolfield_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boolfield',
            name='default',
            field=models.CharField(blank=True, choices=[('0', '是'), ('1', '否'), ('2', '未知')], max_length=10, null=True, verbose_name='默认值'),
        ),
    ]
