# Generated by Django 4.0 on 2022-06-04 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0004_filefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedfield',
            name='related_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='define.relatefieldmodel', verbose_name='关联内容'),
        ),
    ]
