# Generated by Django 4.0 on 2022-02-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0006_managedentity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedfield',
            name='related_content',
        ),
    ]
