# Generated by Django 4.0 on 2023-09-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0006_systemreservedfield_component_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemreservedfield',
            name='name_icpc',
        ),
        migrations.AlterField(
            model_name='systemreservedfield',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='systemreservedfield',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='systemreservedfield',
            name='type',
            field=models.CharField(choices=[('hssc_group_no', '组别'), ('hssc_charge_staff', '责任人'), ('hssc_operator', '作业人员'), ('hssc_scheduled_time', '计划执行时间'), ('hssc_duration', '时长'), ('hssc_frequency', '频次')], max_length=50, verbose_name='系统API字段'),
        ),
    ]
