# Generated by Django 4.0 on 2021-12-15 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0006_rename_available_choice_boolfield_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='字典表名')),
                ('label', models.CharField(max_length=100, verbose_name='字典名称')),
                ('related_field', models.CharField(max_length=100, verbose_name='关联字段')),
            ],
            options={
                'verbose_name': '字典列表',
                'verbose_name_plural': '字典列表',
            },
        ),
        migrations.AlterField(
            model_name='relatedfield',
            name='related_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='define.diclist', verbose_name='关联内容'),
        ),
    ]
