# Generated by Django 4.0 on 2022-01-01 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0006_rename_fields_operandview_mutate_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseform',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='inquireform',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='mutateform',
            name='fields',
        ),
    ]
