# Generated by Django 4.0 on 2023-09-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0007_remove_systemreservedfield_name_icpc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemreservedfield',
            name='type',
            field=models.CharField(choices=[('hssc_group_no', '组别'), ('hssc_charge_staff', '责任人'), ('hssc_operator', '作业人员'), ('hssc_scheduled_time', '计划执行时间'), ('hssc_duration', '天数'), ('hssc_frequency', '频次')], max_length=50, verbose_name='系统API字段'),
        ),
    ]
