# Generated by Django 4.0 on 2021-12-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0007_diclist_alter_relatedfield_related_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='diclist',
            name='content',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='字典内容'),
        ),
    ]
