# Generated by Django 4.0 on 2022-01-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0007_remove_baseform_fields_remove_inquireform_fields_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombineForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='表单名称')),
                ('forms', models.ManyToManyField(blank=True, to='define.CombineForm', verbose_name='可组合的视图')),
            ],
            options={
                'verbose_name': '组合视图',
                'verbose_name_plural': '组合视图',
                'ordering': ['id'],
            },
        ),
    ]
