# Generated by Django 4.0 on 2022-01-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0008_combineform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combineform',
            options={'ordering': ['id'], 'verbose_name': '视图库', 'verbose_name_plural': '视图库'},
        ),
        migrations.AddField(
            model_name='combineform',
            name='is_base',
            field=models.BooleanField(default=False, verbose_name='基础视图'),
        ),
    ]
