# Generated by Django 4.0 on 2022-02-20 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0008_delete_managedentity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['id'], 'verbose_name': '字段汇总清单', 'verbose_name_plural': '字段汇总清单'},
        ),
        migrations.AlterModelOptions(
            name='relatefieldmodel',
            options={'verbose_name': '关联字段基础表', 'verbose_name_plural': '关联字段基础表'},
        ),
    ]
