# Generated by Django 4.0 on 2021-12-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0008_diclist_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operandview',
            name='inquire_forms',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_inquiry': True}, related_name='inquire_forms', to='define.BaseForm', verbose_name='查询视图'),
        ),
    ]
