# Generated by Django 4.0 on 2023-10-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0008_alter_systemreservedfield_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemreservedfield',
            name='system_default',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '当前用户'), (2, '当前时间')], null=True, verbose_name='系统默认值'),
        ),
    ]
