# Generated by Django 4.0 on 2023-10-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0009_systemreservedfield_system_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemreservedfield',
            name='system_default',
        ),
        migrations.AddField(
            model_name='systemreservedfield',
            name='default_value',
            field=models.CharField(blank=True, choices=[('CurrentOperator', '当前用户'), ('SystemTime', '当前时间')], max_length=50, null=True, verbose_name='默认值'),
        ),
    ]
