# Generated by Django 4.0 on 2022-02-22 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0009_alter_component_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatedfield',
            old_name='related_content_new',
            new_name='related_content',
        ),
    ]
