# Generated by Django 4.0 on 2022-01-01 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0009_alter_combineform_options_combineform_is_base'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combineform',
            options={'ordering': ['id'], 'verbose_name': '组合视图', 'verbose_name_plural': '组合视图'},
        ),
        migrations.RemoveField(
            model_name='operandview',
            name='inquire_forms',
        ),
        migrations.RemoveField(
            model_name='operandview',
            name='mutate_forms',
        ),
        migrations.AddField(
            model_name='operandview',
            name='forms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define.combineform', verbose_name='组合视图'),
        ),
    ]
