# Generated by Django 4.0 on 2022-01-01 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0010_alter_combineform_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutateform',
            name='baseforms',
        ),
        migrations.RemoveField(
            model_name='mutateform',
            name='mutateforms',
        ),
        migrations.AddField(
            model_name='combineform',
            name='managed_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define.managedentity', verbose_name='实体类型'),
        ),
        migrations.DeleteModel(
            name='InquireForm',
        ),
        migrations.DeleteModel(
            name='MutateForm',
        ),
    ]
