# Generated by Django 4.0 on 2022-02-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0010_rename_related_content_new_relatedfield_related_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['id'], 'verbose_name': '表单字段汇总', 'verbose_name_plural': '表单字段汇总'},
        ),
        migrations.RemoveField(
            model_name='relatedfield',
            name='related_field',
        ),
        migrations.AlterField(
            model_name='boolfield',
            name='label',
            field=models.CharField(max_length=100, verbose_name='表单字段'),
        ),
        migrations.AlterField(
            model_name='characterfield',
            name='label',
            field=models.CharField(max_length=100, verbose_name='表单字段'),
        ),
        migrations.AlterField(
            model_name='choicefield',
            name='label',
            field=models.CharField(max_length=100, verbose_name='表单字段'),
        ),
        migrations.AlterField(
            model_name='component',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='表单字段'),
        ),
        migrations.AlterField(
            model_name='dtfield',
            name='label',
            field=models.CharField(max_length=100, verbose_name='表单字段'),
        ),
        migrations.AlterField(
            model_name='numberfield',
            name='label',
            field=models.CharField(max_length=100, verbose_name='表单字段'),
        ),
        migrations.AlterField(
            model_name='relatedfield',
            name='label',
            field=models.CharField(max_length=100, unique=True, verbose_name='表单字段'),
        ),
    ]
