# Generated by Django 4.0 on 2022-02-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_icpc', '0006_icpc'),
        ('define', '0011_alter_component_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boolfield',
            name='name_new',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_icpc.icpc', verbose_name='字段名称'),
        ),
        migrations.AddField(
            model_name='characterfield',
            name='name_new',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_icpc.icpc', verbose_name='字段名称'),
        ),
        migrations.AddField(
            model_name='choicefield',
            name='name_new',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_icpc.icpc', verbose_name='字段名称'),
        ),
        migrations.AddField(
            model_name='dtfield',
            name='name_new',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_icpc.icpc', verbose_name='字段名称'),
        ),
        migrations.AddField(
            model_name='numberfield',
            name='name_new',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_icpc.icpc', verbose_name='字段名称'),
        ),
        migrations.AddField(
            model_name='relatedfield',
            name='name_new',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_icpc.icpc', verbose_name='字段名称'),
        ),
        migrations.AddField(
            model_name='relatefieldmodel',
            name='name_new',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_icpc.icpc', verbose_name='字段名称'),
        ),
    ]
