# Generated by Django 4.0 on 2022-01-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0011_remove_mutateform_baseforms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operandview',
            name='mutate_fields',
        ),
        migrations.AddField(
            model_name='combineform',
            name='inquiry_fields',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='查询视图字段'),
        ),
        migrations.AddField(
            model_name='combineform',
            name='mutate_fields',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='变更字段'),
        ),
    ]
