# Generated by Django 4.0 on 2022-02-25 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0012_boolfield_name_new_characterfield_name_new_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boolfield',
            old_name='name_new',
            new_name='name_icpc',
        ),
        migrations.RenameField(
            model_name='characterfield',
            old_name='name_new',
            new_name='name_icpc',
        ),
        migrations.RenameField(
            model_name='choicefield',
            old_name='name_new',
            new_name='name_icpc',
        ),
        migrations.RenameField(
            model_name='dtfield',
            old_name='name_new',
            new_name='name_icpc',
        ),
        migrations.RenameField(
            model_name='numberfield',
            old_name='name_new',
            new_name='name_icpc',
        ),
        migrations.RenameField(
            model_name='relatedfield',
            old_name='name_new',
            new_name='name_icpc',
        ),
        migrations.RenameField(
            model_name='relatefieldmodel',
            old_name='name_new',
            new_name='name_icpc',
        ),
    ]
