# Generated by Django 4.0 on 2022-01-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0012_remove_operandview_mutate_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseform',
            name='fields',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='视图字段'),
        ),
    ]
