# Generated by Django 4.0 on 2022-01-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0013_baseform_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseform',
            name='meta_data',
            field=models.JSONField(blank=True, help_text="格式: {'form_name': ('model_name', ['field_name', ...])}", null=True, verbose_name='视图元数据'),
        ),
        migrations.AddField(
            model_name='combineform',
            name='meta_data',
            field=models.JSONField(blank=True, help_text="格式: [{'form_name': ('model_name', ['field_name', ...])}, ...]", null=True, verbose_name='视图元数据'),
        ),
    ]
