# Generated by Django 4.0 on 2022-03-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_backup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designbackup',
            name='code',
            field=models.TextField(null=True, verbose_name='源代码'),
        ),
        migrations.AlterField(
            model_name='designbackup',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='版本'),
        ),
        migrations.AlterField(
            model_name='icpcbackup',
            name='code',
            field=models.TextField(null=True, verbose_name='源代码'),
        ),
        migrations.AlterField(
            model_name='icpcbackup',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='版本'),
        ),
        migrations.AlterField(
            model_name='sourcecode',
            name='code',
            field=models.TextField(null=True, verbose_name='源代码'),
        ),
        migrations.AlterField(
            model_name='sourcecode',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='版本'),
        ),
    ]
