# Generated by Django 4.0 on 2022-03-06 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_backup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designbackup',
            options={'ordering': ['id'], 'verbose_name': '设计数据备份', 'verbose_name_plural': '设计数据备份'},
        ),
        migrations.AlterModelOptions(
            name='sourcecode',
            options={'ordering': ['id'], 'verbose_name': '作业系统脚本', 'verbose_name_plural': '作业系统脚本'},
        ),
    ]
