# Generated by Django 4.0 on 2023-07-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_backup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcecode',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='域名'),
        ),
    ]
