# Generated by Django 4.0 on 2023-07-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_backup', '0002_sourcecode_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcecode',
            name='domain',
        ),
    ]
