# Generated by Django 4.0 on 2022-02-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_icpc', '0002_icpcbackup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icpc3_symptoms_and_problems',
            name='consider',
            field=models.TextField(blank=True, null=True, verbose_name='考虑'),
        ),
        migrations.AlterField(
            model_name='icpc3_symptoms_and_problems',
            name='criteria',
            field=models.TextField(blank=True, null=True, verbose_name='准则'),
        ),
        migrations.AlterField(
            model_name='icpc3_symptoms_and_problems',
            name='exclude',
            field=models.TextField(blank=True, null=True, verbose_name='排除'),
        ),
        migrations.AlterField(
            model_name='icpc3_symptoms_and_problems',
            name='include',
            field=models.TextField(blank=True, null=True, verbose_name='包含'),
        ),
        migrations.AlterField(
            model_name='icpc3_symptoms_and_problems',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
