# Generated by Django 4.0 on 2022-02-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_icpc', '0005_alter_icpc10_test_results_and_statistics_consider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icpc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icpc_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='icpc码')),
                ('icode', models.CharField(blank=True, max_length=3, null=True, verbose_name='分类码')),
                ('iname', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('iename', models.CharField(blank=True, max_length=255, null=True, verbose_name='English Name')),
                ('include', models.CharField(blank=True, max_length=1024, null=True, verbose_name='包含')),
                ('criteria', models.CharField(blank=True, max_length=1024, null=True, verbose_name='准则')),
                ('exclude', models.CharField(blank=True, max_length=1024, null=True, verbose_name='排除')),
                ('consider', models.CharField(blank=True, max_length=1024, null=True, verbose_name='考虑')),
                ('icd10', models.CharField(blank=True, max_length=8, null=True, verbose_name='ICD10')),
                ('icpc2', models.CharField(blank=True, max_length=10, null=True, verbose_name='ICPC2')),
                ('note', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('subclass', models.CharField(blank=True, max_length=255, null=True, verbose_name='ICPC子类')),
            ],
            options={
                'verbose_name': 'ICPC总表',
                'verbose_name_plural': 'ICPC总表',
            },
        ),
    ]
