# Generated by Django 4.0 on 2022-01-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DicList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='字典表名')),
                ('label', models.CharField(max_length=100, verbose_name='字典名称')),
                ('related_field', models.CharField(max_length=100, verbose_name='关联字段')),
                ('content', models.TextField(blank=True, max_length=1024, null=True, verbose_name='字典内容')),
            ],
            options={
                'verbose_name': '字典列表',
                'verbose_name_plural': '字典列表',
            },
        ),
    ]
