# Generated by Django 4.0 on 2022-03-03 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('define_icpc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='字典表名')),
                ('label', models.CharField(max_length=100, verbose_name='字典名称')),
                ('related_field', models.CharField(max_length=100, verbose_name='关联字段')),
                ('pym', models.CharField(blank=True, max_length=100, null=True, verbose_name='拼音码')),
                ('dic_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='字典ID')),
            ],
            options={
                'verbose_name': '字典列表',
                'verbose_name_plural': '字典列表',
            },
        ),
        migrations.CreateModel(
            name='ManagedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Entity name')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='管理实体名称')),
                ('app_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='实体app名')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='实体model名')),
                ('display_field', models.CharField(blank=True, max_length=100, null=True, verbose_name='显示字段')),
                ('related_field', models.CharField(blank=True, max_length=100, null=True, verbose_name='关联字段')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('entity_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='实体ID')),
            ],
            options={
                'verbose_name': '管理实体清单',
                'verbose_name_plural': '管理实体清单',
            },
        ),
        migrations.CreateModel(
            name='DicDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255, verbose_name='值')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('item_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='字典项目ID')),
                ('diclist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_dict.diclist', verbose_name='字典')),
                ('icpc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='define_icpc.icpc', verbose_name='ICPC')),
            ],
            options={
                'verbose_name': '字典明细',
                'verbose_name_plural': '字典明细',
            },
        ),
    ]
