# Generated by Django 4.0 on 2022-02-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_dict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Entity name')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='管理实体名称')),
                ('app_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='实体app名')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='实体model名')),
                ('display_field', models.CharField(blank=True, max_length=100, null=True, verbose_name='显示字段')),
                ('related_field', models.CharField(blank=True, max_length=100, null=True, verbose_name='关联字段')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '管理实体清单',
                'verbose_name_plural': '管理实体清单',
            },
        ),
    ]
