# Generated by Django 4.0 on 2022-03-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_dict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedentity',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='基本信息表'),
        ),
    ]
