# Generated by Django 4.0 on 2022-03-03 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('define_dict', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diclist',
            name='content',
        ),
    ]
