# Generated by Django 4.0 on 2022-02-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_dict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicdetail',
            name='item_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='字典项目ID'),
        ),
        migrations.AddField(
            model_name='diclist',
            name='dic_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='字典ID'),
        ),
        migrations.AddField(
            model_name='managedentity',
            name='entity_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='实体ID'),
        ),
    ]
