# Generated by Django 4.0 on 2022-02-24 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_icpc', '0006_icpc'),
        ('define_dict', '0002_managedentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255, unique=True, verbose_name='值')),
                ('diclist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='define_dict.diclist', verbose_name='关联字典')),
                ('icpc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='define_icpc.icpc', verbose_name='对应ICPC')),
            ],
            options={
                'verbose_name': '字典明细',
                'verbose_name_plural': '字典明细',
            },
        ),
    ]
