# Generated by Django 4.0 on 2022-02-24 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_icpc', '0006_icpc'),
        ('define_dict', '0004_remove_dicdetail_diclist_remove_dicdetail_icpc'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicdetail',
            name='icpc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='define_icpc.icpc', verbose_name='对应ICPC'),
        ),
    ]
