# Generated by Django 4.0 on 2022-02-24 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_dict', '0005_dicdetail_icpc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicdetail',
            name='icpc',
        ),
        migrations.AddField(
            model_name='dicdetail',
            name='diclist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_dict.diclist', verbose_name='关联字典'),
        ),
        migrations.AlterField(
            model_name='dicdetail',
            name='item',
            field=models.CharField(default='item', max_length=255, unique=True, verbose_name='值'),
        ),
    ]
