# Generated by Django 4.0 on 2022-02-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_dict', '0007_dicdetail_icpc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicdetail',
            name='item',
            field=models.CharField(max_length=255, unique=True, verbose_name='值'),
        ),
    ]
