# Generated by Django 4.0 on 2022-02-24 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('define_icpc', '0006_icpc'),
        ('define_dict', '0008_alter_dicdetail_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicdetail',
            name='diclist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='define_dict.diclist', verbose_name='字典'),
        ),
        migrations.AlterField(
            model_name='dicdetail',
            name='icpc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='define_icpc.icpc', verbose_name='ICPC'),
        ),
    ]
