# Generated by Django 4.0 on 2022-02-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_dict', '0009_alter_dicdetail_diclist_alter_dicdetail_icpc'),
    ]

    operations = [
        migrations.AddField(
            model_name='diclist',
            name='pym',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='拼音码'),
        ),
    ]
