# Generated by Django 4.0 on 2022-02-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_dict', '0010_diclist_pym'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicdetail',
            name='pym',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='拼音码'),
        ),
    ]
