# Generated by Django 4.0 on 2022-02-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_dict', '0011_dicdetail_pym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicdetail',
            name='item',
            field=models.CharField(max_length=255, verbose_name='值'),
        ),
    ]
