# Generated by Django 4.0 on 2022-02-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define_dict', '0012_alter_dicdetail_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicdetail',
            name='pym',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码'),
        ),
    ]
