version: "3"

volumes: # 自定义数据卷
  static_vol: #定义数据卷同步存放web项目static文件夹的数据
  media_vol: #定义数据卷同步存放web项目用户上传到media文件夹的数据
  
networks: # 自定义网络(默认桥接), 不使用links通信
  nginx_network:
    driver: bridge

services:
  nginx:
    build: . # 指定Dockerfile文件所在目录
    # image: nginx-nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
    volumes:
      - ./ssl:/usr/share/nginx/ssl # 挂载ssl证书目录
      - ./log:/var/log/nginx # 挂载日志
      - static_vol:/vol/static # 挂载静态文件
      - media_vol:/vol/media # 挂载用户上传媒体文件
    networks:
      - nginx_network
    restart: always
